Repository kubernetes/release, pull requests merged in 2018-02, with the labels that each got.

#517 Fix pushing bazel built federation release to GCS
  lib/releaselib.sh
  push-build.sh
Labels: cncf-cla: yes, lgtm, sig/multicluster, size/XS

#518 Update the branch time messaging to align with the current process.
  anago
Labels: cncf-cla: yes, lgtm, size/XS

#521 Fix some unset values and messaging.
  gcbmgr
Labels: size/S

#522 If src.tar.gz is found on GCS but not the binaries unset STAGED_* vars.
  anago
Labels: size/XS
