Repository kubernetes/release, pull requests merged in 2018-06, with the labels that each got.

#564 Typo fix in echo message: sucessfully->successfully
  gcbmgr
Labels: cncf-cla: yes, lgtm, size/XS

#562 Typo fix: preceed->precede
  lib/common.sh
Labels: cncf-cla: yes, lgtm, size/XS

#555 Typo fix: commited->committed
  .gitignore
Labels: cncf-cla: yes, lgtm, size/XS

#567 Typo fix: explaination -> explanation
  anago
Labels: cncf-cla: yes, lgtm, size/XS

#565 Add and update kubeadm files for v1.11
  debian/build.go
  debian/build_test.go
  debian/xenial/kubeadm/channel/nightly/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/xenial/kubeadm/channel/stable/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/xenial/kubeadm/channel/unstable/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/xenial/kubelet/debian/kubelet.install
  debian/xenial/kubelet/lib/default/kubelet
  rpm/10-kubeadm-post-1.11.conf
  rpm/kubelet.env
  rpm/kubelet.spec
Labels: cncf-cla: yes, lgtm, sig/release, size/M

#569 Drop @google mailing list from kubernetes release announcements
  lib/releaselib.sh
Labels: cncf-cla: yes, lgtm, size/XS

#570 Adds deb and rpm crictl packages
  debian/build.go
  debian/xenial/cri-tools/debian/changelog
  debian/xenial/cri-tools/debian/compat
  debian/xenial/cri-tools/debian/control
  debian/xenial/cri-tools/debian/copyright
  debian/xenial/cri-tools/debian/cri-tools.install
  debian/xenial/cri-tools/debian/rules
  rpm/kubelet.spec
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#572 Bumps cri-tools to GA version
  debian/build.go
  rpm/kubelet.spec
Labels: cncf-cla: yes, lgtm, size/S

#573 Adds correct dependencies to kubeadm packages
  debian/xenial/kubeadm/debian/control
  rpm/kubelet.spec
Labels: cncf-cla: yes, do-not-merge/hold, lgtm, sig/cluster-lifecycle, size/XS
