Repository kubernetes/release, pull requests merged in 2018-07, with the labels that each got.

#560 Adding GCP COS base image shutdown scripts to GCP k8s release bundle
  lib/releaselib.sh
Labels: cncf-cla: yes, lgtm, size/XS

#578 Add `SECURITY_CONTACTS`
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, sig/release, size/S

#577 create initial OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/S

#588 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#590 anago: push to gcr.io/google-containers
  lib/releaselib.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
