Repository kubernetes/release, pull requests merged in 2018-09, with the labels that each got.

#617 Switch on experimental support in docker CLI
  build/Dockerfile.k8s-cloud-builder
Labels: approved, cncf-cla: yes, lgtm, size/XS

#618 Fix typo in /root/.docker/config.json
  build/Dockerfile.k8s-cloud-builder
Labels: approved, cncf-cla: yes, lgtm, size/XS

#620 Revert image manifest changes
  anago
  build/Dockerfile.k8s-cloud-builder
  lib/releaselib.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#621 Pin cloud-builder base to ubuntu:16.04
  build/Dockerfile.k8s-cloud-builder
Labels: approved, cncf-cla: yes, lgtm, size/XS

#584 Update cri-tools to 1.11.1.
  debian/build.go
  rpm/kubelet.spec
Labels: approved, cncf-cla: yes, lgtm, size/XS

#612 cri-tools only required on >= v1.11
  debian/build.go
  debian/build_test.go
  debian/xenial/kubeadm/debian/control
Labels: approved, cncf-cla: yes, lgtm, size/M

#580 Type fix "created"->"creating"
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#625 Fix RPM Changelog date format
  rpm/kubelet.spec
Labels: approved, cncf-cla: yes, lgtm, size/XS

#627 Add DOCKER_CLI_EXPERIMENTAL flag to enable docker manifest command
  lib/releaselib.sh
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#632 typo fix:is->are
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#630 Better hash algorithms for k8s binaries
  lib/releaselib.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Fix typo: maching -> matching
  lib/gitlib.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#640 Fix kubelet service file permission warning
  rpm/kubelet.spec
Labels: approved, cncf-cla: yes, lgtm, size/XS
