Repository kubernetes/release, pull requests merged in 2019-02, with the labels that each got.

#664 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#661 Add tool for generating contextualized release notes
  BUILD.bazel
  CONTRIBUTING.md
  Gopkg.lock
  README.md
  WORKSPACE
  cmd/release-notes/BUILD.bazel
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  debian/BUILD.bazel
  debian/vendor/github.com/blang/semver/BUILD.bazel
  defs/build.bzl
  defs/deb.bzl
  pkg/notes/BUILD.bazel
  pkg/notes/document.go
  pkg/notes/document_test.go
  pkg/notes/notes.go
  pkg/notes/notes_test.go
  toolbox/relnotes/BUILD.bazel
  toolbox/util/BUILD.bazel
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#648 Remove the duplicated "and"
  lib/releaselib.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#658 Mark the users config file as a config file
  rpm/kubelet.spec
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/cluster-lifecycle, size/XS

#665 delete all duplicate empty blanks
  anago
  branchff
  docs/branching.md
  docs/release-notes.md
  docs/releasing.md
  lib/common.sh
  lib/gitlib.sh
  lib/releaselib.sh
  push-build.sh
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/M

#669 Remove release tracking issue handling
  anago
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/M

#666 Remove obsolete release notes tool files
  toolbox/relnotes/BUILD.bazel
  toolbox/relnotes/README.md
  toolbox/relnotes/build.sh
  toolbox/relnotes/main.go
  toolbox/relnotes/main_test.go
  toolbox/util/BUILD.bazel
  toolbox/util/common.go
  toolbox/util/common_test.go
  toolbox/util/github.go
  toolbox/util/github_test.go
  toolbox/util/gitlib.go
  toolbox/util/gitlib_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#662 upload Windows startup scripts to GCS for releases
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, priority/important-soon, sig/release, size/M

#672 xenial-kubelet: don't install /etc/default/kubelet
  debian/xenial/kubelet/debian/kubelet.install
  debian/xenial/kubelet/lib/default/kubelet
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS
