Repository kubernetes/release, pull requests merged in 2019-05, with the labels that each got.

#710 Add Hannes Hoerl / hhorl / hoegaarden to the patch release team
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#714 updated the links of cherrypick guide
  anago
  docs/branching.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#717 remove build defs from release
  defs/BUILD
  defs/build.bzl
  defs/deb.bzl
  defs/gcs_uploader.py
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#718 remove mikedanese@ as OWNER
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#716 Depends on kubernetes-cni as >=
  debian/build.go
  debian/build_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, sig/release, size/XS

#719 Use bionic instead of xenial as default
  build/Dockerfile.k8s-cloud-builder
  debian/bionic/cri-tools/debian/changelog
  debian/bionic/cri-tools/debian/compat
  debian/bionic/cri-tools/debian/control
  debian/bionic/cri-tools/debian/copyright
  debian/bionic/cri-tools/debian/cri-tools.install
  debian/bionic/cri-tools/debian/rules
  debian/bionic/kubeadm/channel/nightly/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/bionic/kubeadm/channel/nightly/etc/systemd/system/kubelet.service.d/post-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/channel/nightly/etc/systemd/system/kubelet.service.d/pre-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/channel/stable/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/bionic/kubeadm/channel/stable/etc/systemd/system/kubelet.service.d/post-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/channel/stable/etc/systemd/system/kubelet.service.d/pre-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/channel/unstable/etc/systemd/system/kubelet.service.d/post-1.10/10-kubeadm.conf
  debian/bionic/kubeadm/channel/unstable/etc/systemd/system/kubelet.service.d/post-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/channel/unstable/etc/systemd/system/kubelet.service.d/pre-1.8/10-kubeadm.conf
  debian/bionic/kubeadm/debian/changelog
  debian/bionic/kubeadm/debian/compat
  debian/bionic/kubeadm/debian/control
  debian/bionic/kubeadm/debian/copyright
  debian/bionic/kubeadm/debian/kubeadm.install
  debian/bionic/kubeadm/debian/postinst
  debian/bionic/kubeadm/debian/rules
  debian/bionic/kubeadm/debian/source/format
  debian/bionic/kubectl/debian/changelog
  debian/bionic/kubectl/debian/compat
  debian/bionic/kubectl/debian/control
  debian/bionic/kubectl/debian/copyright
  debian/bionic/kubectl/debian/kubectl.install
  debian/bionic/kubectl/debian/postinst
  debian/bionic/kubectl/debian/rules
  debian/bionic/kubectl/debian/source/format
  debian/bionic/kubelet/debian/changelog
  debian/bionic/kubelet/debian/compat
  debian/bionic/kubelet/debian/control
  debian/bionic/kubelet/debian/copyright
  debian/bionic/kubelet/debian/kubelet.install
  debian/bionic/kubelet/debian/postinst
  debian/bionic/kubelet/debian/rules
  debian/bionic/kubelet/debian/source/format
  debian/bionic/kubelet/lib/systemd/system/kubelet.service
  debian/bionic/kubernetes-cni/.gitignore
  debian/bionic/kubernetes-cni/debian/changelog
  debian/bionic/kubernetes-cni/debian/compat
  debian/bionic/kubernetes-cni/debian/control
  debian/bionic/kubernetes-cni/debian/copyright
  debian/bionic/kubernetes-cni/debian/kubernetes-cni.install
  debian/bionic/kubernetes-cni/debian/rules
  debian/build.go
  debian/jessie/kubectl
  debian/precise/kubectl
  debian/sid/kubectl
  debian/stretch/kubectl
  debian/trusty/kubectl
  debian/utopic/kubectl
  debian/vivid/kubectl
  debian/wheezy/kubectl
  debian/wily/kubectl
  debian/xenial
  debian/yakkety/kubectl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#722 removed update-federation-openapi-spec in branchff
  branchff
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#723 Responding to "branchff assumed dependencies #721"
  branchff
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S, tide/merge-method-squash

#727 rpms: change CNI version check to ">="
  rpm/kubelet.spec
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#720 Update debian/ubuntu build definitions
  debian/build.go
  debian/jessie
  debian/jessie/kubectl
  debian/precise/kubectl
  debian/sid
  debian/sid/kubectl
  debian/stretch
  debian/stretch/kubectl
  debian/trusty
  debian/trusty/kubectl
  debian/utopic/kubectl
  debian/vivid/kubectl
  debian/wheezy/kubectl
  debian/wily/kubectl
  debian/yakkety/kubectl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M
