Repository kubernetes/release, pull requests merged in 2019-07, with the labels that each got.

#764 Fixing shellcheck warnings in gcbmgr
  gcbmgr
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#766 One more shellcheck catch for prin
  prin
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#752 Support for OSX and fix some bugs
  prin
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#767 re-add LOCAL_CACHE to lib/common.sh
  lib/common.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#770 Fix mapfile param -t
  prin
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#769 Fixing shellcheck warnings in gitlib_test.sh
  lib/gitlib_test.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#773 Ignore empty arguments
  lib/common.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#772 Fix mapfile param -t in scrpts branchff and prin.
  branchff
  prin
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/XS

#776 Fix common::run_stateful
  lib/BUILD.bazel
  lib/common.sh
  lib/common_test.sh
  lib/gitlib_test.sh
  lib/releaselib_test.sh
  lib/testing.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#784 Fixing shellcheck warnings in entry.sh
  rpm/entry.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#782 Fixing shellcheck warnings in release-notify
  release-notify
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-longterm, sig/release, size/S

#783 Fixing shellcheck warnings in docker-build
  rpm/docker-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#785 Fixing shellcheck warnings in script-template
  script-template
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#775 Ensure branchff stops if check_binaries fails
  branchff
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/XS

#781 Fixing shellcheck warnings in relnotes
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/L

#768 Fixing shellcheck warnings in gitlib.sh
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/M

#758 Fixing shellcheck warnings in anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/L

#778 Fixing shellcheck warnings in releaselib.sh
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/L

#780 Fixing shellcheck warnings in releaselib_test.sh
  lib/releaselib_test.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/S

#787 Fixing arrays after shellcheck cleanup
  lib/common.sh
  prin
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/XS

#790 Fixing mapfile to use -t instead of -i argument
  lib/common.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, sig/release, size/XS

#791 anago: Fix instance where shellcheck comment breaks newline
  anago
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#794 lib: Fixing releaselib issues
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, sig/release, size/XS

#795 Fixing mapfile empty array error in releaselib
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#792 shellcheck: Fix can't follow non-constant source (SC1090/SC1091)
  lib/common_test.sh
  lib/gitlib_test.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#797 Fixing quotes around tarfile path
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/XS

#771 Update shebangs to `#!/usr/bin/env bash`
  anago
  branchff
  changelog-update
  debian/jenkins.sh
  find_green_build
  gcbmgr
  lib/common.sh
  lib/gitlib.sh
  lib/gitlib_test.sh
  lib/releaselib.sh
  lib/releaselib_test.sh
  release-notify
  relnotes
  rpm/docker-build.sh
  script-template
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#800 Fix build break - Deal better with wild cards
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#801 Update GCB KMS
  gcb/release.yaml
  gcb/stage.yaml
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#802 Fix build break - mapfile use and stray double quote
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#803 lib/gitlib: Fix shellcheck disable for gitlib::github_acls
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#804 lib/releaselib: Swap non-positional options in find command
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#805 fixed `K8S_GITHUB_API` in anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#807 Fix typo in GHCURL request
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#808 fixed `K8S_GITHUB_API` in anago followup of PR-805
  anago
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#799 Fixing Branch Manager Handbook url in README.md
  README.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#810 Trim token & correct PRs URL
  anago
  lib/gitlib.sh
  lib/gitlib_test.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M, tide/merge-method-squash

#814 Revert recent changes to stabilize CI and release tooling
  anago
  branchff
  changelog-update
  debian/jenkins.sh
  find_green_build
  gcbmgr
  lib/BUILD.bazel
  lib/common.sh
  lib/gitlib.sh
  lib/gitlib_test.sh
  lib/releaselib.sh
  lib/releaselib_test.sh
  prin
  push-build.sh
  release-notify
  relnotes
  rpm/docker-build.sh
  rpm/entry.sh
  script-template
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#815 lib/gitlib: Reapply GITHUB_TOKEN whitespace trim
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#819 gitlib: fix handling of remote url
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#738 Update minimum supported dependencies for debs/rpms
  debian/build.go
  debian/build_test.go
  rpm/10-kubeadm-post-1.8.conf
  rpm/10-kubeadm-pre-1.8.conf
  rpm/kubelet.spec
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/L, ¯\_(ツ)_/¯

#820 Verify deb/rpm packages exist in Kubernetes apt/yum repos
  Makefile
  hack/packages/verify-published.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#822 Makefile: Disable shellcheck verify to clear up CI
  Makefile
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#817 Set all shebangs to #!/usr/bin/env bash
  anago
  branchff
  changelog-update
  debian/jenkins.sh
  find_green_build
  gcbmgr
  lib/common.sh
  lib/gitlib.sh
  lib/gitlib_test.sh
  lib/releaselib.sh
  lib/releaselib_test.sh
  prin
  release-notify
  relnotes
  rpm/docker-build.sh
  rpm/entry.sh
  script-template
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#824 hack/packages: Fix indentation issue with rpm repo info
  hack/packages/verify-published.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#789 Add Unit Tests to Makefile
  Makefile
  hack/test-go.sh
  hack/test-sh.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#827 release: keep images in registry if PURGE_IMAGES=no
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#832 Fix `common::run_gobin` function documentation
  lib/common.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#833 Improve note parsing
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/M

#830 Beautify markdown for multi-line release notes
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#835 Follow Cherry Pick PRs to their original Release Note
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, priority/important-soon, sig/release, size/S

#798 Fix shell script tests
  anago
  lib/BUILD.bazel
  lib/common_test.sh
  lib/gitlib.sh
  lib/gitlib_test.sh
  lib/releaselib.sh
  lib/releaselib_test.sh
  lib/testing.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L, tide/merge-method-squash

#812 Fix git checkout and kube cross
  anago
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M
