Repository kubernetes/release, pull requests merged in 2019-11, with the labels that each got.

#916 Intoduce root options for krel root command
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/root.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, sig/release, size/M

#909 [prototype] Stage/release Kubernetes on k8s-infra - Phase 0
  anago
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  gcbmgr
  lib/releaselib.sh
  push-build.sh
  release-notify
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#905 Add push-build go version skeleton
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/push.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#917 Add command validation to utils and ff command
  cmd/krel/cmd/ff.go
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#919 Use shell parameter substitution to convert GCP_USER value to lowercase
  gcbmgr
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#920 Move notes git implementation into dedicated package
  BUILD.bazel
  cmd/release-notes/BUILD.bazel
  cmd/release-notes/main.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/notes/BUILD.bazel
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#922 Add command package and tests
  BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/ff.go
  pkg/command/BUILD.bazel
  pkg/command/command.go
  pkg/command/command_test.go
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#924 Minor cleanup of krel ff and supporting git library
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/ff.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/util/BUILD.bazel
  pkg/util/git.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#925 testgridshot: Update usage doc to include vgy.me registration link
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#926 Update build commands in README
  README.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#927 Update repo to go1.13.4
  build/debs/Dockerfile
  build/debs/go.mod
  go.mod
  images/godep/Dockerfile
  images/godep/README.md
  images/godep/cloudbuild.yaml
  images/k8s-cloud-builder/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, sig/release, size/M

#928 Remove leftovers from the godep image
  Makefile
  images/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS

#929 Update CONTRIBUTING.md to reflect use of go modules
  .gitignore
  CONTRIBUTING.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#886 Improved resolution of PR from commit SHA
  pkg/notes/notes.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/M

#936 Bind git branch verification to `Repo`
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/root.go
  cmd/release-notes/main.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#937 Refactor the rest of the git methods
  cmd/krel/cmd/ff.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#938 Add DescribeTag method for Repo
  cmd/krel/cmd/ff.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#934 switch to python3, remove python2
  gcbmgr
  images/k8s-cloud-builder/Dockerfile
  images/k8s-cloud-builder/cloudbuild.yaml
  images/k8s-cloud-builder/test.yaml
  lib/common.sh
  lib/gitlib.sh
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/M

#939 Make branch ff ready to be used
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/ff.go
  pkg/git/git.go
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#942 Add git package unit tests
  pkg/command/command.go
  pkg/command/command_test.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#943 [testgridshot] upload images to a bucket
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/M, tide/merge-method-squash

#947 Add golangci-lint and enable successful linters
  .golangci.yml
  BUILD.bazel
  WORKSPACE
  go.mod
  go.sum
  hack/tools.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#948 Apply first batch of golangci linters
  .golangci.yml
  cmd/blocking-testgrid-tests/main.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/push.go
  cmd/krel/cmd/root.go
  cmd/release-notes/main.go
  pkg/command/command.go
  pkg/git/git.go
  pkg/notes/notes.go
  pkg/notes/notes_test.go
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-longterm, sig/release, size/L
