Repository kubernetes/release, pull requests merged in 2020-06, with the labels that each got.

#1330 kubepkg: Bundle CNI plugins (v0.8.6) in kubelet deb/rpm packages
  cmd/kubepkg/templates/latest/deb/kubelet/debian/control
  cmd/kubepkg/templates/latest/deb/kubelet/debian/kubelet.install
  cmd/kubepkg/templates/latest/deb/kubelet/debian/rules
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/.gitignore
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/changelog
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/compat
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/control
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/copyright
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/kubernetes-cni.install
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/rules
  cmd/kubepkg/templates/latest/rpm/kubelet/kubelet.spec
  cmd/kubepkg/templates/latest/rpm/kubernetes-cni/kubernetes-cni.spec
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/kubepkg/options/options.go
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/network, sig/release, size/L

#1332 Fix kubepkg options parsing
  cmd/kubepkg/cmd/debs.go
  cmd/kubepkg/cmd/root.go
  cmd/kubepkg/cmd/rpms.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/regression, lgtm, needs-priority, release-note, sig/release, size/M

#1334 Fix invalid previous tag on krel changelog for beta releases > 0
  pkg/github/github.go
  pkg/github/github_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/regression, lgtm, needs-priority, release-note, sig/release, size/S

#1328 fix typos
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, ok-to-test, release-note-none, sig/release, size/XS

#1340 docs: Update gcbmgr usage
  cmd/krel/cmd/gcbmgr.go
  docs/krel/gcbmgr.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/M

#1341 Fix release-notes TOC to contain dependency report
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1326 Remove FLAGS_gcb from anago
  anago
  cmd/krel/cmd/anago.go
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1338 gh2gcs: add initial documentation
  cmd/gh2gcs/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/M

#1313 cmd/schedule-builder: Add CLI tool for release schedule generation
  BUILD.bazel
  cmd/schedule-builder/BUILD.bazel
  cmd/schedule-builder/README.md
  cmd/schedule-builder/cmd/BUILD.bazel
  cmd/schedule-builder/cmd/root.go
  cmd/schedule-builder/main.go
  compile-release-tools
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/L

#1337 gh2gcs: add download only option
  cmd/gh2gcs/cmd/root.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1339 kube-cross: Build v1.14.4-1 image
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note

#1336 OWNERS: Add Release Manager Associates as release-engineering-reviewers
  OWNERS
  OWNERS_ALIASES
  cmd/kubepkg/OWNERS
  images/OWNERS
  packages/deb/OWNERS
  packages/rpm/OWNERS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1343 gh2gcs: update wording
  cmd/gh2gcs/cmd/root.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1346 k8s-cloud-builder: Build cross1.14 variant on kube-cross:v1.14.4-1
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1347 kube-cross: bump to go1.13.12
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/XS

#1350 krel release-notes refactor & cleanup
  cmd/krel/cmd/release_notes.go
  pkg/github/github.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1357 deps: update several dependencies
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1344 gh2gcs: Download release assets in parallel
  go.mod
  go.sum
  pkg/github/BUILD.bazel
  pkg/github/github.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1356 Update krel release-notes documentation
  docs/krel/release-notes.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/M

#1349 schedule-builder: add some unit tests
  cmd/schedule-builder/cmd/BUILD.bazel
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
  cmd/schedule-builder/cmd/model.go
  cmd/schedule-builder/cmd/root.go
  cmd/schedule-builder/cmd/root_test.go
  cmd/schedule-builder/cmd/testdata/bad_schedule.yaml
  cmd/schedule-builder/cmd/testdata/schedule.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1358 HACK: temporarily skip git push
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/XS

#1359 packages/deb: Use go modules instead of vendor in build Dockerfile
  packages/deb/Dockerfile
  packages/deb/go.mod
  packages/deb/go.sum
  packages/deb/jenkins.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/S

#1360 HACK: tags still conflict even if we don't push
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/S

#1363 revert Anago hacks
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/critical-urgent, release-note-none, sig/release, size/S

#1364 krel: clarify announce subcommand help
  cmd/krel/cmd/announce.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1372 kube-cross: Build v1.14.4-2 and v1.13.12-2 images
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/S

#1374 k8s-cloud-builder: Build cross1.14 variant on kube-cross:v1.14.4-2
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, sig/release, size/XS

#1375 packages: Reintroduce kubernetes-cni package at v0.8.6
  packages/deb/bionic/kubelet/debian/control
  packages/deb/bionic/kubelet/debian/kubelet.install
  packages/deb/bionic/kubelet/debian/rules
  packages/deb/bionic/kubernetes-cni/.gitignore
  packages/deb/bionic/kubernetes-cni/debian/changelog
  packages/deb/bionic/kubernetes-cni/debian/compat
  packages/deb/bionic/kubernetes-cni/debian/control
  packages/deb/bionic/kubernetes-cni/debian/copyright
  packages/deb/bionic/kubernetes-cni/debian/kubernetes-cni.install
  packages/deb/bionic/kubernetes-cni/debian/rules
  packages/deb/build.go
  packages/deb/build_test.go
  packages/rpm/kubelet.spec
Labels: approved, area/release-eng, cncf-cla: yes, kind/regression, lgtm, priority/critical-urgent, release-note, sig/release, size/L

#1376 Move Notes and Kind type into notes package
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1377 Add record/replay functionality to github.GetReleaseByTag
  pkg/github/record.go
  pkg/github/replay.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1378 add k8s-rapture.sh script for publishing debs/rpms to rapture
  hack/k8s-rapture.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1351 Make hack/verify-shellcheck.sh work with podman
  hack/verify-shellcheck.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1308 Add GetJobCache function from releaselib.sh
  pkg/gcp/gcp.go
  pkg/release/BUILD.bazel
  pkg/release/build_version.go
  pkg/release/build_version_data_test.go
  pkg/release/build_version_test.go
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_gcp_client.go
  pkg/release/repository.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1379 Fix broken kubepkg deb build test
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/kubepkg/kubepkgfakes/fake_impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note, sig/release, size/L

#1381 kubepkg: Restore kubernetes-cni package templates
  cmd/kubepkg/templates/latest/deb/kubelet/debian/control
  cmd/kubepkg/templates/latest/deb/kubelet/debian/kubelet.install
  cmd/kubepkg/templates/latest/deb/kubelet/debian/rules
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/.gitignore
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/changelog
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/compat
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/control
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/copyright
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/kubernetes-cni.install
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/rules
  cmd/kubepkg/templates/latest/rpm/kubelet/kubelet.spec
  cmd/kubepkg/templates/latest/rpm/kubernetes-cni/kubernetes-cni.spec
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/kubepkg/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1380 gh2gcs: add yaml config option
  cmd/gh2gcs/cmd/BUILD.bazel
  cmd/gh2gcs/cmd/root.go
  go.mod
  pkg/gcp/gcs/gcs.go
  pkg/gh2gcs/BUILD.bazel
  pkg/gh2gcs/gh2gcs.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1383 kubepkg: Use the cross build version marker (ci/k8s-master) for packages
  pkg/kubepkg/kubepkg.go
  pkg/release/version.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, needs-priority, release-note, sig/release, size/XS
