Repository kubernetes/release, pull requests merged in 2020-01, with the labels that each got.

#997 lint: Additional lint cleanups for Go files
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/push.go
  cmd/release-notes/main.go
  pkg/notes/client.go
  pkg/notes/internal/retry_test.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notesfakes/fake_client.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#998 kubepkg: Support templating package specs and add skeleton for rpm building
  build/debs/packages/latest/kubectl/debian/control
  build/debs/templates/latest/cri-tools/debian/changelog
  build/debs/templates/latest/cri-tools/debian/compat
  build/debs/templates/latest/cri-tools/debian/control
  build/debs/templates/latest/cri-tools/debian/copyright
  build/debs/templates/latest/cri-tools/debian/cri-tools.install
  build/debs/templates/latest/cri-tools/debian/rules
  build/debs/templates/latest/kubeadm/10-kubeadm.conf
  build/debs/templates/latest/kubeadm/debian/changelog
  build/debs/templates/latest/kubeadm/debian/compat
  build/debs/templates/latest/kubeadm/debian/control
  build/debs/templates/latest/kubeadm/debian/copyright
  build/debs/templates/latest/kubeadm/debian/kubeadm.install
  build/debs/templates/latest/kubeadm/debian/postinst
  build/debs/templates/latest/kubeadm/debian/rules
  build/debs/templates/latest/kubeadm/debian/source/format
  build/debs/templates/latest/kubectl/debian/changelog
  build/debs/templates/latest/kubectl/debian/compat
  build/debs/templates/latest/kubectl/debian/control
  build/debs/templates/latest/kubectl/debian/copyright
  build/debs/templates/latest/kubectl/debian/kubectl.install
  build/debs/templates/latest/kubectl/debian/postinst
  build/debs/templates/latest/kubectl/debian/rules
  build/debs/templates/latest/kubectl/debian/source/format
  build/debs/templates/latest/kubelet/debian/changelog
  build/debs/templates/latest/kubelet/debian/compat
  build/debs/templates/latest/kubelet/debian/control
  build/debs/templates/latest/kubelet/debian/copyright
  build/debs/templates/latest/kubelet/debian/kubelet.install
  build/debs/templates/latest/kubelet/debian/postinst
  build/debs/templates/latest/kubelet/debian/rules
  build/debs/templates/latest/kubelet/debian/source/format
  build/debs/templates/latest/kubelet/lib/systemd/system/kubelet.service
  build/debs/templates/latest/kubernetes-cni/.gitignore
  build/debs/templates/latest/kubernetes-cni/debian/changelog
  build/debs/templates/latest/kubernetes-cni/debian/compat
  build/debs/templates/latest/kubernetes-cni/debian/control
  build/debs/templates/latest/kubernetes-cni/debian/copyright
  build/debs/templates/latest/kubernetes-cni/debian/kubernetes-cni.install
  build/debs/templates/latest/kubernetes-cni/debian/rules
  build/rpms/.gitignore
  build/rpms/10-kubeadm-post-1.8.conf
  build/rpms/10-kubeadm-pre-1.8.conf
  build/rpms/kubelet.spec
  build/rpms/templates/latest/cri-tools/cri-tools.spec
  build/rpms/templates/latest/kubeadm/10-kubeadm.conf
  build/rpms/templates/latest/kubeadm/kubeadm.spec
  build/rpms/templates/latest/kubectl/kubectl.spec
  build/rpms/templates/latest/kubelet/kubelet.env
  build/rpms/templates/latest/kubelet/kubelet.service
  build/rpms/templates/latest/kubelet/kubelet.spec
  build/rpms/templates/latest/kubernetes-cni/kubernetes-cni.spec
  cmd/kubepkg/cmd/BUILD.bazel
  cmd/kubepkg/cmd/root.go
  cmd/kubepkg/cmd/rpms.go
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/kubepkg/template.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#980 Add table of contents support
  cmd/release-notes/main.go
  pkg/notes/BUILD.bazel
  pkg/notes/options.go
  pkg/notes/toc.go
  pkg/notes/toc_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#992 Add markdown creation support for krel changelog
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#921 branchff: Remove hack/update-openapi-spec.sh run from tool
  branchff
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/M

#930 Use testgrid config from github.com/GoogleCloudPlatform
  cmd/blocking-testgrid-tests/BUILD.bazel
  cmd/blocking-testgrid-tests/main.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/XXL

#1006 add initial and basic tests for krel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog_test.go
  cmd/krel/cmd/root_test.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1002 Add bazel container image which includes build-essentials
  images/README.md
  images/releng-ci-bazel/Dockerfile
  images/releng-ci-bazel/cloudbuild.yaml
  images/releng-ci-bazel/test.yaml
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#931 Add make target to update our go dependencies
  Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/M

#1004 Fix and adapt linter config
  .golangci.yml
  cmd/krel/cmd/push.go
  cmd/kubepkg/cmd/debs.go
  cmd/kubepkg/cmd/rpms.go
  cmd/release-notes/main.go
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/notes/client.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/options.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1009 Update dependencies and cleanup go.mod
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#999 Fix minor-to-latest discovery mode start revision selection
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/notes/options.go
  pkg/notes/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1005 Add HTML output to `krel changelog`
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1012 Fix unparam lint issue in notes gatherer test
  pkg/notes/notes_gatherer_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1003 Add changelog remote lookup feature
  cmd/krel/cmd/changelog.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/notes/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1013 anago: Remove OpenAPI spec version bump logic
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/critical-urgent, sig/release, size/L

#1015 anago: Ensure ordered releases by using a sorted release key array
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/critical-urgent, sig/release, size/M

#1022 kubepkg: Update inputs and expected values for TestFetchVersionSuccess
  pkg/kubepkg/kubepkg_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/XS

#923 Sort release notes by Kind(s) instead of SIG(s)
  pkg/notes/document.go
  pkg/notes/document_test.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/docs, sig/release, size/L

#1014 Add commit support for changelog subcommand
  cmd/krel/cmd/changelog.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1025 Restore checked out branch in krel changelog
  cmd/krel/cmd/changelog.go
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1026 anago: emit more debug output
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1033 [testgridshot] Fix after testgrid changed the summary endpoint
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, sig/release, size/XS

#1017 Split-up git test into unit and integration parts
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/git_test.go
  pkg/git/gitfakes/BUILD.bazel
  pkg/git/gitfakes/fake_repository.go
  pkg/git/gitfakes/fake_worktree.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#1018 [k8s-cloud-builder] Add gcc to image to support multi-arch (cross-building)
  gcb/build/cloudbuild.yaml
  images/k8s-cloud-builder/Dockerfile
  images/k8s-cloud-builder/cloudbuild.yaml
  images/k8s-cloud-builder/test.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, priority/important-longterm, sig/release, size/S

#1030 anago: Unconditionally add an empty commit prior to release tagging
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, sig/release, size/S

#1032 Update golangci-lint to v1.23.1
  .golangci.yml
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XXL

#1024 Fix release notes heading for failing-test kinds
  pkg/notes/document.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1035 Add GO111MODULE environment variable to example
  cmd/release-notes/README.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1036 Log the PR number if release notes parsing failed for a commit
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1034 Change krel changelog to not push any more
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1038 Use GITHUB_TOKEN env var instead of CLI flag
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1042 Add dedicated --html-file output option to krel changelog
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1045 Fix golangci-lint CI
  .golangci.yml
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1041 Add log filename hook to krel/release-notes
  BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/root.go
  cmd/release-notes/BUILD.bazel
  cmd/release-notes/main.go
  pkg/log/BUILD.bazel
  pkg/log/hooks.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1047 compile-release-tools: Update script to compile all release tools
  compile-release-tools
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1043 Add git -rm CHANGELOG-*.md to krel changelog
  cmd/krel/cmd/changelog.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1046 Add `krel version` subcommand and make target
  BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/version.go
  compile-release-tools
  pkg/version/BUILD.bazel
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1050 Add record/replay flags to `krel changelog`
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1048 Use GOPATH instead of GOBIN in compile-release-tools
  compile-release-tools
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1052 gcbmgr: Add flag/support for attended GCB build submissions
  gcbmgr
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS
