Repository kubernetes/release, pull requests merged in 2020-04, with the labels that each got.

#1199 [VDF] anago: Publish container images on K8s Infra (k8s-staging-kubernetes)
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, sig/release, size/L

#1228 Find files and directories when pushing binaries to GCS
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/XS

#1229 [VDF] Partial revert of k8s.gcr.io cutover
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1231 Quarterly OWNERS updates
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1233 Add kind/regression to issue template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1235 gcbmgr: default list job variable to 5 if a negative number was set
  cmd/krel/cmd/gcbmgr.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, release-note, sig/release, size/XS

#1232 Add support for kind/regression
  cmd/krel/cmd/changelog_data_test.go
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/document/testdata/document.md.golden
  pkg/notes/document/testdata/document_without_downloads.md.golden
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1238 dependencies/google.golang.org/api: update google.golang.org/api to v0.21.0
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1240 dependencies/testgrid: update to use release v0.0.10
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1237 dependencies/cobra: update cobra to v0.0.7
  cmd/krel/cmd/root_test.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1243 Fix version based unit tests
  cmd/krel/cmd/gcbmgr_test.go
  pkg/release/version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, sig/release, size/S

#1242 images: add skopeo binary for the 1.15 releases
  images/k8s-cloud-builder/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1244 Make release version retrieval tests independent up remote content
  cmd/krel/cmd/gcbmgr.go
  pkg/kubepkg/kubepkg.go
  pkg/release/BUILD.bazel
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_version_client.go
  pkg/release/version.go
  pkg/release/version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, sig/release, size/L

#1246 kube-cross: Update to go1.14.2
  images/build/cross/Dockerfile
  images/build/cross/VERSION
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/XS

#1247 Make gcbmgr tests independent from remote content
  cmd/krel/cmd/cmdfakes/BUILD.bazel
  cmd/krel/cmd/cmdfakes/fake_version.go
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, sig/release, size/L

#1245 Add a patch-to-latest discover mode
  cmd/release-notes/README.md
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1249 kubelet.service: Wait for network-online.target
  cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service
  cmd/kubepkg/templates/latest/rpm/kubelet/kubelet.service
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-longterm, release-note, sig/node, sig/release, size/XS

#1252 Add ls-remote to git package
  pkg/git/git.go
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M
