Repository kubernetes/release, pull requests merged in 2020-11, with the labels that each got.

#1667 vulndash: Add page size when listing vulnerabilities more logs and build v0.3.0 image
  cmd/vulndash/Makefile
  cmd/vulndash/cmd/root.go
  cmd/vulndash/variants.yaml
  dependencies.yaml
  pkg/vulndash/adapter/adapter.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/design, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1664 Add `tar` package
  pkg/release/release.go
  pkg/tar/tar.go
  pkg/tar/tar_test.go
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1668 vulndash: set Default page size and small test refactor
  pkg/vulndash/adapter/adapter.go
  pkg/vulndash/adapter/adapter_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1670 Remove cip-mm from krel and use new CIP packages
  cmd/krel/cmd/promote-images.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1659 Add isPushableBranch() function to determine which branches are pushed
  cmd/krel/cmd/anago/push_git_objects.go
  cmd/krel/cmd/anago/push_git_objects_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1669 Release Notes Maps tests and other fixes
  pkg/notes/maps/testdata/fullmap.yaml
  pkg/notes/maps/testdata/unit/maps.yaml
  pkg/notes/notes_map.go
  pkg/notes/notes_map_test.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1671 Cobra-ify cip-mm
  cmd/cip-mm/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1658 Push git objects using new go code
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1661 Move anago 'stage source tree' step into 'krel anago push'
  anago
  cmd/krel/cmd/anago/push.go
  pkg/release/push.go
  pkg/tar/tar.go
  pkg/tar/tar_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1674 Add tar.Extract() API
  pkg/tar/tar.go
  pkg/tar/tar_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1675 Use tar and gcs APIs for GCP build
  pkg/gcp/build/build.go
  pkg/gcp/gcp.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1676 Rename gSUtilExecutable -> gsutilExecutable
  pkg/gcp/gcp.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1678 Update golang dependencies
  go.mod
  go.sum
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1679 images: Build releng-ci:v0.1.1 image
  dependencies.yaml
  images/releng/ci/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1681 Update release confirmation message to show expected yes/no input
  cmd/krel/cmd/gcbmgr.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1680 Remove unused bash from anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1677 Migrate workspace preparation to krel
  anago
  cmd/krel/cmd/anago/prepare_workspace.go
  lib/gitlib.sh
  lib/releaselib.sh
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/gitfakes/fake_repository.go
  pkg/release/push.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/release/workspace.go
  pkg/tar/tar.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1683 Move `krel changelog` logic into separate package
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_test.go
  pkg/changelog/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/design, lgtm, needs-priority, release-note-none, sig/release, size/XXL

#1685 Add generic krel stage/release options
  cmd/krel/cmd/release.go
  cmd/krel/cmd/stage.go
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/release.go
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1638 Take `NoUpdateLatest` into account for krel push
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1644 Add krel push `Version` option
  cmd/krel/cmd/anago/push.go
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1686 Integrate workspace preparation into `krel release`
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/release/release.go
  pkg/release/workspace.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1688 Add workspace preparation for `krel stage`
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1691 Migrate gitlib::push_master to golang
  anago
  cmd/krel/cmd/anago/push_git_objects.go
  lib/gitlib.sh
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/release/push_git_objects.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1689 Add release version and artifacts push to krel stage/release
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/release/release.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XXL

#1692 Add build to `krel stage`
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/build/buildfakes/fake_impl.go
  pkg/build/make.go
  pkg/build/make_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1702 Add changelog generation to krel stage
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1704 Support updating the GitHub release page from the announce page
  pkg/announce/github_page.go
  pkg/github/github.go
  pkg/github/githubfakes/fake_client.go
  pkg/github/record.go
  pkg/github/replay.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1701 Log git clone output only on debug/trace log level
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1706 Fix krel stage local source tree archiving
  cmd/krel/cmd/anago/push.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/build/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1695 Pass --log-level via `krel gcbmgr`
  cmd/krel/cmd/gcbmgr.go
  gcb/release-krel/cloudbuild.yaml
  gcb/stage-krel/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XS

#1700 Cleanup some CI build logic and add k8s-ci-builder image
  cmd/krel/cmd/ci_build.go
  cmd/krel/cmd/push.go
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/variants.yaml
  pkg/build/build.go
  pkg/build/ci.go
  pkg/build/push.go
  pkg/release/publish.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1708 Add release message to krel stage
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1709 Determine correct changelog branch for krel stage
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1710 k8s-ci-builder: Clean up image building configs
  cmd/krel/cmd/anago/push.go
  cmd/krel/cmd/ci_build.go
  cmd/krel/cmd/push.go
  docs/krel/push.md
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/create_bazel_cache_rcs.sh
  images/releng/k8s-ci-builder/install-bazel.sh
  images/releng/k8s-ci-builder/variants.yaml
  images/releng/k8s-ci-builder/wrapper.sh
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/build/build.go
  pkg/build/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XL

#1713 pkg/build: Validate images exist before proceeding with CI builds
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/variants.yaml
  pkg/build/ci.go
  pkg/release/images.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1716 krel/cloudbuild: defautl disk size request to 500Gb
  cmd/krel/cmd/gcbmgr.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/release, size/XS

#1717 Add git.Tags() API
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/release/push_git_objects.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, kind/regression, lgtm, needs-priority, release-note, sig/release, size/S

#1718 gcp/build: output the command that will send to gcp cloudbuild
  pkg/gcp/build/build.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1719 Use utility function to parse semver
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1720 Remove double mock generation in krel gcbmgr
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1721 Add gcb package
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_history.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
  pkg/gcp/gcb/gcbfakes/fake_list_jobs.go
  pkg/gcp/gcb/gcbfakes/fake_repository.go
  pkg/gcp/gcb/gcbfakes/fake_version.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XXL

#1707 Add tag repository support to krel stage
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/gitfakes/fake_repository.go
  pkg/git/gitfakes/fake_worktree.go
  pkg/release/release_version.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1725 Simplify rapture steps for a new version
  hack/rapture/README.md
  hack/rapture/check_rapture.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/S

#1727 Fix GCP double copy
  pkg/build/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/release, size/S

#1729 pkg/git: remove sensitive data when returning errors that will be output
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/S

#1730 Create an empty repo when testing git pusher
  pkg/release/push_git_objects_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1731 krel: Properly handle jobs with GCS Suffix set and don't attempt to set ACLs on K8s Infra buckets
  cmd/krel/cmd/anago/push.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/build/build.go
  pkg/build/ci.go
  pkg/build/push.go
  pkg/gcp/gcs/gcs.go
  pkg/release/publish.go
  pkg/release/publish_test.go
  pkg/release/releasefakes/fake_command_client.go
  pkg/release/releasefakes/fake_publisher_client.go
  pkg/release/releasefakes/fake_repository.go
  pkg/release/releasefakes/fake_version_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1723 Remove `mgr` from `gcb` package
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1714 dependencies: update several dependencies
  go.mod
  go.sum
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1715 Do not escape `#` in notes any more
  cmd/krel/cmd/changelog_data_test.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1726 Add process State to Stage and Release
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1732 Build images using go1.15.5
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1733 Rename GCB `Run()` method to `Submit()`
  cmd/krel/cmd/gcbmgr.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1722 Rename SetClient to SetImpl for stage/release impls
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1728 Enable verbose git output for krel stage/release
  pkg/git/git.go
  pkg/tar/tar.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1735 Move krel `--cleanup` and `--repo-path` flags into subcommands
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/ff_test.go
  cmd/krel/cmd/release_notes.go
  cmd/krel/cmd/root.go
  cmd/krel/cmd/sut_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-kind, needs-priority, release-note-none, sig/release, size/M

#1734 Allow submitting jobs via krel stage/release
  cmd/krel/cmd/release.go
  cmd/krel/cmd/stage.go
  gcb/release-krel/cloudbuild.yaml
  gcb/stage-krel/cloudbuild.yaml
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/gcp/build/build.go
  pkg/gcp/gcb/gcb.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1696 [krel] Introduce krel subcommand to screenshot testgrid dashboards
  README.md
  cmd/krel/cmd/testgrid.go
  go.mod
  go.sum
  pkg/http/http.go
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1736 Always push remote branch
  pkg/release/push_git_objects.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1697 Integrate CreateAnnouncement() and PushGitObjects() into krel release
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/release/push_git_objects.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1738 pkg/gcp/gcs: Improve GCS path construction/retrieval logic
  cmd/krel/cmd/ci_build.go
  cmd/krel/cmd/push.go
  dependencies.yaml
  pkg/anago/release.go
  pkg/build/build.go
  pkg/build/ci.go
  pkg/build/push.go
  pkg/gcp/gcs/gcs.go
  pkg/gcp/gcs/gcs_test.go
  pkg/release/publish.go
  pkg/release/publish_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XL

#1741 Add progress count to krel stage/release
  pkg/anago/anago.go
  pkg/anago/release.go
  pkg/log/step.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1737 Enhance log-level and nomock flag docs
  cmd/gcbuilder/cmd/root.go
  cmd/gh2gcs/cmd/root.go
  cmd/krel/cmd/anago/push_git_objects.go
  cmd/krel/cmd/root.go
  cmd/kubepkg/cmd/root.go
  cmd/schedule-builder/cmd/root.go
  cmd/vulndash/cmd/root.go
  pkg/log/log.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/M

#1742 pkg/build: Fully remove GCSSuffix option
  cmd/krel/cmd/ci_build.go
  cmd/krel/cmd/push.go
  pkg/build/build.go
  pkg/gcp/gcs/gcs.go
  pkg/release/images.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1746 Add GCS bucket to release artifacts push
  cmd/krel/cmd/anago/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1748 Pass correct gcsRoot in release PublishVersion()
  pkg/anago/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1749 Pass correct gcsRoot in krel anago push
  cmd/krel/cmd/anago/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1751 Allow spec with gs:// prefix in URLPrefixForBucket()
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1752 images: Build go-runner:buster-v2.2.1
  dependencies.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1756 vulndash: Add debug logs
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  pkg/vulndash/adapter/adapter.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1753 Add release branch verification
  pkg/release/branch_checker.go
  pkg/release/branch_checker_test.go
  pkg/release/releasefakes/fake_branch_checker_impl.go
  pkg/release/releasefakes/fake_command_client.go
  pkg/release/releasefakes/fake_publisher_client.go
  pkg/release/releasefakes/fake_repository.go
  pkg/release/releasefakes/fake_version_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1740 Make krel stage/release parentBranch a bool
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1747 Fix staging location to contain the bucket
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1754 Integrate branch state check into krel stage/release
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1757 Remove HasBranch check for krel stage tagging
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1758 GCS object store implementation
  Makefile
  cmd/gh2gcs/cmd/root.go
  cmd/krel/cmd/testgrid.go
  pkg/build/build.go
  pkg/build/ci.go
  pkg/build/push.go
  pkg/gcp/build/build.go
  pkg/gh2gcs/gh2gcs.go
  pkg/object/gcs.go
  pkg/object/gcs_test.go
  pkg/object/store.go
  pkg/release/publish.go
  pkg/release/release.go
  pkg/release/workspace.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, kind/cleanup, kind/design, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1759 Move `krel gcbmgr history` implementation into pkg
  cmd/krel/cmd/gcbmgr_history.go
  pkg/gcp/gcb/history.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1760 Make push-build.sh independent
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1761 Add GCB history unit tests
  pkg/gcp/gcb/gcbfakes/fake_history_impl.go
  pkg/gcp/gcb/history.go
  pkg/gcp/gcb/history_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1764 Add prerequisites check to krel stage/release
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/release/prerequisites.go
  pkg/release/prerequisites_test.go
  pkg/release/releasefakes/fake_command_client.go
  pkg/release/releasefakes/fake_prerequisites_checker_impl.go
  pkg/release/releasefakes/fake_publisher_client.go
  pkg/release/releasefakes/fake_repository.go
  pkg/release/releasefakes/fake_version_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1766 OWNERS: Update SIG leadership and Release Managers (promotions, new members, retirement)
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1771 kpromo: Add file promotion and manifest generation functionality
  OWNERS_ALIASES
  cmd/kpromo/OWNERS
  cmd/kpromo/README.md
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/manifest/manifest.go
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/run/files.go
  cmd/kpromo/cmd/run/run.go
  cmd/kpromo/main.go
  cmd/promobot-files/OWNERS
  cmd/promobot-files/README.md
  cmd/promobot-files/main.go
  cmd/promobot-generate-manifest/OWNERS
  cmd/promobot-generate-manifest/README.md
  cmd/promobot-generate-manifest/main.go
  compile-release-tools
  pkg/cip/OWNERS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1772 Refactor image promoter tests to use github.com/stretchr/testify
  pkg/cip/audit/auditor_test.go
  pkg/cip/dockerregistry/checks_test.go
  pkg/cip/dockerregistry/grow_manifest_test.go
  pkg/cip/dockerregistry/inventory_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XL

#1770 cip-mm: replace klog to use k/release/pkg/log
  cmd/cip-mm/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1755 [krel] gcbmgr should forbid nomock stage/releases on user forks
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcbfakes/fake_repository.go
  pkg/release/repository.go
  pkg/release/repository_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, ok-to-test, release-note-none, sig/release, size/M

#1768 Release Archiver
  pkg/object/gcs.go
  pkg/release/archive.go
  pkg/release/archive_test.go
  pkg/release/archive_unit_test.go
  pkg/release/releasefakes/fake_archiver_impl.go
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1775 Fix krel history default dates
  pkg/gcp/gcb/history.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1773 Reuse object.GcsPrefix where possible
  pkg/api/files/validation.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/notes/notes_map.go
  pkg/object/gcs.go
  pkg/release/publish.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1776 Reference `krel release` in output
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1778 Remove unused FakeGOPATH function
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1777 Add disk space check to krel stage/release
  go.mod
  go.sum
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/release/prerequisites.go
  pkg/release/prerequisites_test.go
  pkg/release/releasefakes/fake_archiver_impl.go
  pkg/release/releasefakes/fake_prerequisites_checker_impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/L

#1779 Only restore branch if available
  pkg/changelog/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1774 Add log file support to krel stage/release
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1780 go-runner: Build buster-v2.2.2 image
  dependencies.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1785 Do not echo fatal messages in GCB on krel compilation
  compile-release-tools
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1781 Remove GitHub tokens in util.StripSensitiveData()
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1784 Update k8s-cloud-builder to v1.15.5-1
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1782 Fix git configure for krel release
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/release/prerequisites.go
  pkg/release/prerequisites_test.go
  pkg/release/releasefakes/fake_prerequisites_checker_impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/L

#1745 Add unit tests to changelog package
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
  pkg/changelog/changelog.go
  pkg/changelog/changelog_test.go
  pkg/changelog/changelogfakes/fake_impl.go
  pkg/changelog/const.go
  pkg/changelog/impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XXL

#1763 Add `--stream` flag to krel stage/release
  cmd/krel/cmd/release.go
  cmd/krel/cmd/stage.go
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_stage_client.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1783 Remove BUILD_POINT in favor of BUILD_VERSION
  gcb/release-krel/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage-krel/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1787 OWNERS: Update krel approvers/reviewers
  OWNERS_ALIASES
  cmd/cip-mm/OWNERS
  pkg/api/OWNERS
  pkg/promobot/OWNERS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1788 .github/ISSUE_TEMPLATE: Add template for updating Golang dependencies
  .github/ISSUE_TEMPLATE/dep-golang.md
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/L

#1769 krel: integrate release archiver
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/release/archive.go
  pkg/release/archive_test.go
  pkg/release/archive_unit_test.go
  pkg/release/release.go
  pkg/release/releasefakes/fake_archiver_impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1790 Use correct release GCB substitutions
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
  pkg/gcp/gcb/gcbfakes/fake_release.go
  pkg/gcp/gcb/gcbfakes/fake_repository.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/L

#1791 Disable noClobber for uploading source tree tarball
  pkg/build/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1789 Update the release GitHub page from krel
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/announce/github_page.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1765 Remove anago
  Makefile
  README.md
  anago
  cmd/krel/cmd/anago/anago.go
  cmd/krel/cmd/anago/generate_release_version.go
  cmd/krel/cmd/anago/generate_release_version_test.go
  cmd/krel/cmd/anago/prepare_workspace.go
  cmd/krel/cmd/anago/push.go
  cmd/krel/cmd/anago/push_git_objects.go
  cmd/krel/cmd/anago/push_git_objects_test.go
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_history.go
  cmd/krel/cmd/history.go
  cmd/krel/cmd/root.go
  docs/krel/README.md
  docs/krel/gcbmgr.md
  docs/krel/gcbmgr_history.md
  docs/release-notes.md
  gcb/release-krel/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage-krel/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  images/README.md
  lib/common.sh
  lib/common_test.sh
  lib/gitlib.sh
  lib/gitlib_test.sh
  lib/releaselib.sh
  lib/testdata/common/shas/SHA256SUMS
  lib/testdata/common/shas/SHA512SUMS
  lib/testdata/common/shas/shafile1.txt
  lib/testdata/common/shas/shafile1.txt.md5
  lib/testdata/common/shas/shafile1.txt.sha1
  lib/testdata/common/shas/shafile1.txt.sha256
  lib/testdata/common/shas/shafile1.txt.sha512
  lib/testdata/common/shas/shafile2.txt
  lib/testdata/common/shas/shafile2.txt.md5
  lib/testdata/common/shas/shafile2.txt.sha1
  lib/testdata/common/shas/shafile2.txt.sha256
  lib/testdata/common/shas/shafile2.txt.sha512
  lib/testdata/gitlib/create_issue.txt
  lib/testdata/gitlib/create_issue_milestone.txt
  lib/testdata/gitlib/create_publishing_bot_issue.txt
  lib/testdata/gitlib/create_publishing_bot_issue_nomock.txt
  lib/testdata/gitlib/create_publishing_bot_issue_nomock_noassign.txt
  lib/testing.sh
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/build/push.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcb_test.go
  pkg/gcp/gcb/history.go
  pkg/release/images.go
  pkg/release/publish.go
  pkg/release/release.go
  pkg/release/workspace.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XXL

#1794 Add update-mocks Makefile target
  Makefile
  pkg/anago/anagofakes/fake_release_client.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/changelog/changelogfakes/fake_impl.go
  pkg/kubepkg/kubepkgfakes/fake_impl.go
  pkg/mail/mailfakes/fake_apiclient.go
  pkg/mail/mailfakes/fake_send_client.go
  pkg/notes/notesfakes/fake_mo_diff.go
  pkg/object/objectfakes/fake_store.go
  pkg/release/releasefakes/fake_archiver_impl.go
  pkg/testgrid/testgridfakes/fake_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1796 Add `Env()` API to `command` package
  pkg/command/command.go
  pkg/command/command_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1797 Fix gcb TODO
  pkg/gcp/gcb/gcb.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1744 Moving fastforward from cmd to pkg
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/ff_test.go
  cmd/krel/cmd/sut_test.go
  pkg/fastforward/fastforward.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, ok-to-test, release-note-none, sig/release, size/L

#1798 pkg/cip: Drop klog v1 dependency
  go.mod
  pkg/cip/audit/auditor.go
  pkg/cip/dockerregistry/checks.go
  pkg/cip/dockerregistry/grow_manifest.go
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/gcloud/token.go
  pkg/cip/remotemanifest/git.go
  pkg/cip/report/gcp.go
  pkg/cip/stream/http.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1793 pkg/cip: Use cenkalti/backoff/v4 to remove dep on k8s.io/apimachinery
  go.mod
  go.sum
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/stream/types.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1799 cip: calling the function by passing the parameters by pointer
  cmd/cip-mm/main.go
  cmd/krel/cmd/promote-images.go
  pkg/cip/dockerregistry/grow_manifest.go
  pkg/cip/dockerregistry/grow_manifest_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/S

#1800 promobot: replace klog to use logrus
  pkg/promobot/promotefiles.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1801 Removing klog lib in favor of logrus
  go.mod
  go.sum
  pkg/cip/audit/auditor.go
  pkg/cip/dockerregistry/checks.go
  pkg/cip/dockerregistry/grow_manifest.go
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/gcloud/token.go
  pkg/cip/remotemanifest/git.go
  pkg/cip/report/gcp.go
  pkg/cip/stream/http.go
  pkg/filepromoter/file.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/filepromoter/manifest.go
  pkg/filepromoter/token.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1802 cip: calling some functions by passing the parameters by pointer
  pkg/cip/audit/auditor.go
  pkg/cip/audit/auditor_test.go
  pkg/cip/audit/types.go
  pkg/cip/dockerregistry/checks.go
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/dockerregistry/inventory_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1803 Update README.md
  README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/L

#1804 pkg/cip: Add `cli` package
  pkg/cip/cli/audit.go
  pkg/cip/cli/root.go
  pkg/cip/cli/run.go
  pkg/cip/cli/version.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1805 Add release notes JSON to artifacts
  pkg/anago/stage.go
  pkg/changelog/changelog.go
  pkg/changelog/changelog_test.go
  pkg/changelog/changelogfakes/fake_impl.go
  pkg/changelog/impl.go
  pkg/object/objectfakes/fake_store.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1806 pkg/cip: Use --no-dry-run instead of --dry-run
  pkg/cip/cli/root.go
  pkg/cip/cli/run.go
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/dockerregistry/types.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/release, size/M
