Repository kubernetes/release, pull requests merged in 2020-09, with the labels that each got.

#1511 Bootstrap docker buildx usage for multiarch containers
  hack/init-buildx.sh
  images/build/go-runner/Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1514 images: Build go1.15.1 images (kube-cross, go-runner)
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1512 hack: Improve comment on 'docker-container' driver usage for buildx
  hack/init-buildx.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1516 images: Build k8s-cloud-builder:v1.15.1-1
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1489 Always require --buildversion for anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1515 Update CNI plugins to v0.8.7
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
  packages/deb/build.go
  packages/rpm/kubelet.spec
  pkg/kubepkg/kubepkg.go
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1520 Remove `release-version` flag and option
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  pkg/notes/notes.go
  pkg/notes/notes_map.go
  pkg/notes/notes_test.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/M

#1513 Remove find_green_build and all of its dependencies
  BUILD.bazel
  anago
  cmd/blocking-testgrid-tests/BUILD.bazel
  cmd/blocking-testgrid-tests/main.go
  cmd/krel/cmd/gcbmgr.go
  find_green_build
  lib/common.sh
  lib/releaselib.sh
  pkg/release/BUILD.bazel
  pkg/release/build_version.go
  pkg/release/build_version_data_test.go
  pkg/release/build_version_test.go
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_gcp_client.go
  pkg/release/releasefakes/fake_github_client.go
  pkg/release/releasefakes/fake_job_cache_client.go
  pkg/release/releasefakes/fake_test_grid_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XXL

#1523 Fix compile-release-tools by removing blocking-testgrid-tests
  compile-release-tools
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/XS

#1519 schedule-builder: fix bug when path release is next and are in the previous patch list
  cmd/schedule-builder/README.md
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1454 New function util.WrapText() and updates to util.Ask()
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1522 Add krel set-release-version command to be used in anago
  anago
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/set_release_version.go
  cmd/krel/cmd/set_release_version_test.go
  lib/releaselib.sh
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1524 Make `krel set-release-version` a subcmd of `krel anago`
  anago
  cmd/krel/cmd/anago.go
  cmd/krel/cmd/set_release_version.go
  cmd/krel/cmd/set_release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1525 Replace most of the `master` terminology with git.DefaultBranch
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_test.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/ff_test.go
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  cmd/krel/cmd/release_notes.go
  cmd/krel/cmd/set_release_version_test.go
  cmd/krel/cmd/sut_test.go
  cmd/release-notes/main.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/git_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
  pkg/release/version.go
  pkg/testgrid/testgrid_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1526 Fix incorrect label ID for alpha and beta releases
  cmd/krel/cmd/set_release_version_test.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1527 Document gh2gcs use case and SIG Release managed buckets
  cmd/gh2gcs/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/S

#1528 Update command to reflect prodaccess depreciation
  hack/rapture/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1530 testgrid: check if need to upload the images
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1467 [krel] Release Notes Editing Flow
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/release_notes.go
  go.mod
  go.sum
  pkg/notes/notes.go
  pkg/notes/notes_map.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1418 images: Use docker buildx for kube-cross images and consolidate go-based image Makefiles
  dependencies.yaml
  images/Makefile.common-image
  images/build/Makefile.build-image
  images/build/cross/Makefile
  images/build/cross/cloudbuild.yaml
  images/build/cross/variants.yaml
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-hyperkube-base/cloudbuild.yaml
  images/build/debian-iptables/cloudbuild.yaml
  images/build/go-runner/Dockerfile
  images/build/go-runner/Makefile
  images/build/go-runner/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1502 krel/announcement: Add krel command to build the Kubernetes announcement file
  anago
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/announce.go
  cmd/krel/cmd/announce_build.go
  cmd/krel/cmd/announce_send.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1533 images: Build kube-cross:v1.15.2-1 and go-runner:buster-v2.0.2 (using go1.15.2)
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1537 images: Build debian-base:v1.2.0
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1539 Streamline krel push error messages
  cmd/krel/cmd/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1540 images: Build debian-iptables:buster-v1.3.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/buster/Dockerfile
  images/build/debian-iptables/cloudbuild.yaml
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1541 debian-iptables: Install ebtables from buster-backports
  images/build/cross/cloudbuild.yaml
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-hyperkube-base/cloudbuild.yaml
  images/build/debian-iptables/buster/Dockerfile
  images/build/debian-iptables/cloudbuild.yaml
  images/build/go-runner/cloudbuild.yaml
  images/k8s-cloud-builder/cloudbuild.yaml
  images/releng-ci-bazel/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1542 images: Build debian-hyperbase-base:buster-v1.2.0
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1543 [krel] Change --org and --*-repo flags to --fork in release-notes subcmd
  cmd/krel/cmd/release_notes.go
  docs/krel/release-notes.md
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, kind/bug, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/L

#1549 anago: fix bad substitution
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1550 images: Build k8s-cloud-builder:v1.15.2-1
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1529 Add links to rapture RPM/Debian lists
  hack/rapture/README.md
  hack/rapture/check_rapture.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/M, tide/merge-method-squash

#1552 images/releng/ci: Use Golang as the base image for CI
  dependencies.yaml
  images/README.md
  images/releng/ci/Dockerfile
  images/releng/ci/cloudbuild.yaml
  images/releng/ci/test.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1433 Remove bazel from k/release
  .bazelrc
  .kazelcfg.json
  BUILD.bazel
  WORKSPACE
  cmd/gcbuilder/BUILD.bazel
  cmd/gcbuilder/cmd/BUILD.bazel
  cmd/gh2gcs/BUILD.bazel
  cmd/gh2gcs/cmd/BUILD.bazel
  cmd/krel/BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/cmdfakes/BUILD.bazel
  cmd/kubepkg/BUILD.bazel
  cmd/kubepkg/cmd/BUILD.bazel
  cmd/release-notes/BUILD.bazel
  cmd/schedule-builder/BUILD.bazel
  cmd/schedule-builder/cmd/BUILD.bazel
  images/build/go-runner/BUILD.bazel
  lib/BUILD.bazel
  packages/deb/BUILD.bazel
  pkg/announce/BUILD.bazel
  pkg/command/BUILD.bazel
  pkg/gcp/BUILD.bazel
  pkg/gcp/auth/BUILD.bazel
  pkg/gcp/build/BUILD.bazel
  pkg/gcp/gcs/BUILD.bazel
  pkg/gh2gcs/BUILD.bazel
  pkg/git/BUILD.bazel
  pkg/git/gitfakes/BUILD.bazel
  pkg/github/BUILD.bazel
  pkg/github/githubfakes/BUILD.bazel
  pkg/github/internal/BUILD.bazel
  pkg/http/BUILD.bazel
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkgfakes/BUILD.bazel
  pkg/kubepkg/options/BUILD.bazel
  pkg/log/BUILD.bazel
  pkg/mail/BUILD.bazel
  pkg/mail/mailfakes/BUILD.bazel
  pkg/notes/BUILD.bazel
  pkg/notes/document/BUILD.bazel
  pkg/notes/internal/BUILD.bazel
  pkg/notes/notesfakes/BUILD.bazel
  pkg/notes/options/BUILD.bazel
  pkg/release/BUILD.bazel
  pkg/release/regex/BUILD.bazel
  pkg/release/releasefakes/BUILD.bazel
  pkg/testgrid/BUILD.bazel
  pkg/testgrid/testgridfakes/BUILD.bazel
  pkg/testing/BUILD.bazel
  pkg/util/BUILD.bazel
  pkg/version/BUILD.bazel
  repos.bzl
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XXL

#1553 Update all repo dependencies
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  packages/deb/go.mod
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1555 Fix golangci-lint check and update config
  .golangci.yml
  pkg/testgrid/testgrid_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, sig/release, size/S

#1554 Remove bazel-based ./hack scripts
  Makefile
  dependencies.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-all.sh
  hack/verify-all.sh
  hack/verify-golangci-lint.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XL

#1558 Add configurable timeout to test-go.sh
  hack/test-go.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1486 Add release.GetImageTags() and GetOCIManifest() functions
  go.mod
  go.sum
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1559 Increase Go Tests timeout to 30min
  hack/test-go.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1532 Rename `SetReleaseVersion` to be `GetBuildVersion`
  anago
  cmd/krel/cmd/generate_release_version.go
  cmd/krel/cmd/generate_release_version_test.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1560 Fix $CHANGELOG_PATH for krel announce
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1557 Add make verify-boilerplate check
  Makefile
  dependencies.yaml
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/verify-boilerplate.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1538 Add binary copy function to `krel push`
  cmd/krel/cmd/push.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1563 Remove bazel go module dependency
  go.mod
  go.sum
  pkg/notes/document/document_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1566 Apply gofumpt formatter and enable via golang-ci-lint
  .golangci.yml
  cmd/krel/cmd/anago.go
  cmd/krel/cmd/announce_build.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/release_notes.go
  pkg/gcp/build/build.go
  pkg/git/git_test.go
  pkg/github/github_test.go
  pkg/notes/notes.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1564 Reflect latest bazel changes in docs
  CONTRIBUTING.md
  cmd/release-notes/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/S

#1562 Implement checksum write for `krel push`
  cmd/krel/cmd/push.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1567 Copy artifacts to GCS in `krel push`
  cmd/gh2gcs/cmd/root.go
  cmd/krel/cmd/push.go
  pkg/gcp/gcs/gcs.go
  pkg/gh2gcs/gh2gcs.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/M

#1544 [krel] krel promote-images subcommand
  cmd/krel/cmd/promote-images.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1568 Add container image publishing to krel push
  cmd/krel/cmd/push.go
  pkg/release/images.go
  pkg/release/images_test.go
  pkg/release/release.go
  pkg/release/releasefakes/fake_command_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1570 Remove unreachable code paths in releaselib.sh
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1571 Fix anago checks for buildversion
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/S

#1574 Add release publish to to krel push
  .golangci.yml
  cmd/krel/cmd/push.go
  pkg/gcp/gcp.go
  pkg/release/images.go
  pkg/release/publish.go
  pkg/release/publish_test.go
  pkg/release/regex/regex.go
  pkg/release/releasefakes/fake_publisher_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1575 Add --fast support for krel push
  cmd/krel/cmd/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1579 Move krel push logic into release API
  cmd/krel/cmd/push.go
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XL

#1581 Use semver for release version generation
  pkg/release/regex/regex.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1582 Migrate image validation to golang
  cmd/krel/cmd/promote-images.go
  cmd/krel/cmd/push.go
  pkg/release/images.go
  pkg/release/images_test.go
  pkg/release/push.go
  pkg/release/release.go
  pkg/release/releasefakes/fake_command_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1583 Support fast flag in publish
  pkg/release/publish.go
  pkg/release/publish_test.go
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1584 Remove prin and sample script
  lib/common.sh
  prin
  script-template
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1585 Fix double colon in image publishing
  pkg/release/images.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1586 Make default build dir an internal const
  cmd/krel/cmd/push.go
  pkg/release/push.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1587 Remove --release-type flag from krel push
  cmd/krel/cmd/push.go
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1590 dependencies: update some dependencies
  go.mod
  go.sum
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1592 Clean up tools list in README
  README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1591 contributing: update basic scripts to run before submiting a PR
  CONTRIBUTING.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1593 pkg/release: Add StageLocalArtifacts API to krel push
  .golangci.yml
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1589 krel/gcbmgr: add build-at-head flag
  cmd/krel/cmd/gcbmgr.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1588 images/k8s-cloud-builder: Update skopeo to v1.2.0
  images/k8s-cloud-builder/Dockerfile
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1596 Move anago subcommands to own directory
  cmd/krel/cmd/anago/anago.go
  cmd/krel/cmd/anago/generate_release_version.go
  cmd/krel/cmd/anago/generate_release_version_test.go
  cmd/krel/cmd/root.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1601 Remove update-all.sh script from Makefile target
  Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1602 Remove `nomock` option from krel push
  cmd/krel/cmd/push.go
  pkg/release/publish.go
  pkg/release/publish_test.go
  pkg/release/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1599 New editor to remove k8s.io/kubectl/pkg/cmd/util/editor dependency
  cmd/krel/cmd/release_notes.go
  go.mod
  go.sum
  pkg/editor/editor.go
  pkg/editor/editor_test.go
  pkg/editor/tty.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1598 Remove k8s.io/apimachinery dependency
  go.mod
  go.sum
  pkg/github/github.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L
