Repository kubernetes/release, pull requests merged in 2020-02, with the labels that each got.

#1051 Repo update should persist repo state
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/ff.go
  pkg/command/command.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1049 Add `krel version` precheck to anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1044 Use krel changelog instead of relnotes bash script
  anago
  lib/common.sh
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/L

#1054 Remove unused `AwsSdkVersion` variable
  pkg/version/version.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1055 Update golangci-lint to v1.23.3
  .golangci.yml
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1056 Do not pull changes before changelog generation
  cmd/krel/cmd/changelog.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1053 Fix compile-release-tools execution for GCB builds
  anago
  compile-release-tools
  gcb/release/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1058 Fix changelog generation for anago usage
  anago
  cmd/krel/cmd/changelog.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1059 Fix gcbmgr KUBE_CROSS_VERSION env var passing
  gcbmgr
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1060 Use filename hook only for debug levels
  pkg/log/hooks.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/XS

#1057 Add local-image-{build,run} Makefile targets
  Makefile
  images/k8s-cloud-builder/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/S

#1062 Print the path where specs are saved if Spec-only mode is selected
  pkg/kubepkg/kubepkg.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, sig/release, size/XS

#1063 .github: Add PR/issue templates and security notice
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1069 Make SIG list more compact
  pkg/notes/document.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS

#1072 Trim leading and trailing whitespace from rendered markdown
  cmd/krel/cmd/changelog.go
  pkg/notes/document.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS

#1070 Rename ListCommitsWithNotes and make method private
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/M

#1066 Update go-github to v29
  go.mod
  go.sum
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkg.go
  pkg/notes/BUILD.bazel
  pkg/notes/client/BUILD.bazel
  pkg/notes/client/client.go
  pkg/notes/client/clientfakes/BUILD.bazel
  pkg/notes/client/clientfakes/fake_client.go
  pkg/notes/client/record.go
  pkg/notes/client/replay.go
  pkg/notes/internal/BUILD.bazel
  pkg/notes/internal/retry.go
  pkg/notes/internal/retry_test.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_test.go
  pkg/notes/options/BUILD.bazel
  pkg/notes/options/options.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/M

#1071 Sort release notes alphabetically
  pkg/notes/document.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, sig/release, size/XS

#1073 Add dedicated release notes section for 'action required' notes
  pkg/notes/document.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, sig/release, size/S

#1075 Uppercase the first character for each markdown note
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, sig/release, size/XS

#1074 Bind `RenderMarkdown` function to `*Document`
  cmd/krel/cmd/changelog.go
  cmd/release-notes/main.go
  pkg/notes/document.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/S

#1081 Fork test-infra gcbuilder and initial commit of krel gcbmgr
  BUILD.bazel
  cmd/gcbuilder/BUILD.bazel
  cmd/gcbuilder/Dockerfile
  cmd/gcbuilder/Makefile
  cmd/gcbuilder/README.md
  cmd/gcbuilder/ci-runner.sh
  cmd/gcbuilder/cloudbuild.yaml
  cmd/gcbuilder/cmd/BUILD.bazel
  cmd/gcbuilder/cmd/root.go
  cmd/gcbuilder/cmd/root_test.go
  cmd/gcbuilder/main.go
  cmd/gcbuilder/run.sh
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/gcbmgr.go
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  go.mod
  go.sum
  pkg/gcp/build/BUILD.bazel
  pkg/gcp/build/build.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XXL

#1082 Makefile: Add targets for running krel gcbmgr in CI
  Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/S

#1083 Use tag from changelogOpts instead of function argument
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1064 Fix CHANGELOG-x.y.md paths for new subpath
  cmd/krel/cmd/changelog.go
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, sig/release, size/M

#1084 Allow only GITHUB_TOKEN env var
  cmd/krel/cmd/changelog.go
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1086 Remove unnecessary double-init of the logger
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/version.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1090 Revert common and command pkg to using go1.12 compatible vars
  cmd/krel/cmd/changelog.go
  cmd/release-notes/main.go
  pkg/command/command.go
  pkg/git/git_integration_test.go
  pkg/kubepkg/kubepkg.go
  pkg/notes/client/record.go
  pkg/notes/document_test.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  pkg/release/release_test.go
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/M

#1085 Add initial krel release-notes implementation
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1091 jenkins.sh: fix race condition against process substitution
  debian/jenkins.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/release, size/XS

#1092 Truly use the latest tag as default EndRev
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1077 lib/release: Parameterize GCP projects and GCS bucket names
  gcbmgr
  lib/releaselib.sh
  push-build.sh
  release-notify
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/M

#1093 Update krel changelog docs to mention GITHUB_TOKEN and repo path
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/S

#1094 Fix missing CHANGELOG/CHANGELOG* locations
  README.md
  anago
  cmd/kubepkg/templates/latest/deb/kubeadm/debian/changelog
  cmd/kubepkg/templates/latest/deb/kubectl/debian/changelog
  cmd/kubepkg/templates/latest/deb/kubelet/debian/changelog
  cmd/kubepkg/templates/latest/deb/kubernetes-cni/debian/changelog
  docs/release-notes.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1096 anago: Only create empty release commits on release branches
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/M

#1097 Add Run{Silent}SuccessOutput API to command
  cmd/krel/cmd/release_notes.go
  pkg/command/command.go
  pkg/command/command_test.go
  pkg/gcp/auth/auth.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/L

#1095 Remove deprecated --requiredAuthor flag
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1079 push-build: Stop invoking bazel to get version file
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/XS

#1098 pkg/command: leave the underlying WaitStatus type opaque
  pkg/command/command.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/backlog, release-note-none, sig/release, size/S

#1099 Set authoritative changelog location and update release announcements copy
  anago
  lib/releaselib.sh
  relnotes
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, kind/documentation, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1101 [krel] gcbmgr: Add support for 'release' workflow
  cmd/gcbuilder/cmd/root.go
  cmd/gcbuilder/cmd/root_test.go
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  pkg/command/command.go
  pkg/command/command_test.go
  pkg/gcp/auth/auth.go
  pkg/gcp/build/build.go
  pkg/release/BUILD.bazel
  pkg/release/release.go
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XL

#1104 [krel] gcbmgr: Address bartsmykla review comments
  cmd/krel/cmd/gcbmgr.go
  pkg/gcp/auth/auth.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/M

#1103 Allow gcbmgr to execute with ssh remote
  gcbmgr
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XS

#1105 [krel] Add release artifacts staging to krel push
  cmd/krel/cmd/push.go
  pkg/release/release.go
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note-none, sig/release, size/XL

#1108 Use OutputTrimNL in git package
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1109 Fix gcbmgr cloudbuild clone step with https remote
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  gcbmgr
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note-none, sig/release, size/M

#1113 Configure git user for releng-ci-bazel test image
  images/releng-ci-bazel/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1115 pkg/git: Add getters for GitHub URLs
  cmd/krel/cmd/release_notes.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/L

#1114 [krel] gcbmgr: Dynamically retrieve build version from CI markers
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
  pkg/release/BUILD.bazel
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/XL

#1116 Remove `owner` from git.CloneOrOpenDefaultGitHubRepoSSH function
  cmd/krel/cmd/ff.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1111 Add krel ff integration tests
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/ff_test.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1118 Make git.Remotify idempotent
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1102 Implement clone, commit and push of release notes draft to user's fork
  cmd/krel/cmd/release_notes.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1123 Restore checked out branch on krel ff
  cmd/krel/cmd/ff.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1124 krel/ff: print a shorter git commit hash
  cmd/krel/cmd/ff.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, release-note, sig/release, size/XS

#1125 util/common: add new line when printing to std out to avoid messages in the same line
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, release-note, sig/release, size/XS

#1121 Default release notes fork repo to 'sig-release'
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1122 Test for available fork remotes before adding them
  cmd/krel/cmd/release_notes.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/gitfakes/fake_repository.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1120 Add tests for git.AddRemote and git.PushToRemote
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1117 Fix --ref for krel ff and enhance documentation
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/ff_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1127 krel/ff: remove not needed quote
  cmd/krel/cmd/ff.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1130 Sort git.Remotes() by their name per default
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1131 Cleanup ff pre-push message function
  cmd/krel/cmd/ff.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1128 Remove federation options in krel push
  cmd/krel/cmd/push.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1135 Fix latest tag retrieval for krel changelog
  cmd/krel/cmd/changelog.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1138 Add krel help and mention it in the README.md
  README.md
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/push.go
  cmd/krel/cmd/release_notes.go
  cmd/krel/cmd/root.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/S
