Repository kubernetes/release, pull requests merged in 2020-08, with the labels that each got.

#1455 anago: Push images during staging and validate manifests during release
  anago
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  images/build/cross/Makefile
  images/k8s-cloud-builder/Dockerfile
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/regression, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1456 base-images: Build debian-iptables@v12.1.1
  dependencies.yaml
  images/build/debian-iptables/Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1458 base-images: Build debian-hyperkube-base@v1.1.2
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1457 lib/release: Ensure production images have been promoted in validation step
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1462 Correct typo in krel installation documentation
  docs/krel/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1397 Add release.SetReleaseVersion API
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/release/BUILD.bazel
  pkg/release/build_version.go
  pkg/release/regex/BUILD.bazel
  pkg/release/regex/regex.go
  pkg/release/release_version.go
  pkg/release/release_version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1463 Update pull request template to match latest prow capabilities
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1453 New functions git.GetUserName and git.GetUserEmail
  pkg/git/git.go
  pkg/git/git_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1451 anago: set the Golang version used to build the release when creating the announcement
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1469 Use existing GitHub API for release.SetBuildVersion()
  pkg/release/BUILD.bazel
  pkg/release/build_version.go
  pkg/release/build_version_test.go
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_github_client.go
  pkg/release/releasefakes/fake_http_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1470 gh2gcs: when copying the package to cloud storage use the tag to set the path in the destination
  pkg/gh2gcs/gh2gcs.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1471 Log extra version markers when publishing release
  lib/releaselib.sh
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1473 kube-cross: Build v1.14.7-1 and v1.13.15-1 images
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/XS

#1475 k8s-cloud-builder: Build on kube-cross:v1.14.7-1 and v1.13.15-1
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1476 images/build/debian-**: Enable variant building and build debian-base@v1.1.0
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-base/v1/Dockerfile
  images/build/debian-base/v1/Dockerfile.build
  images/build/debian-base/v1/clean-install
  images/build/debian-base/v1/excludes
  images/build/debian-base/v2/Dockerfile
  images/build/debian-base/v2/Dockerfile.build
  images/build/debian-base/v2/clean-install
  images/build/debian-base/v2/excludes
  images/build/debian-base/variants.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/cloudbuild.yaml
  images/build/debian-iptables/v11/Dockerfile
  images/build/debian-iptables/v11/iptables-wrapper
  images/build/debian-iptables/v12/Dockerfile
  images/build/debian-iptables/v12/iptables-wrapper
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, sig/release, size/L

#1478 images: Build debian-base:v2.1.3 and debian-iptables:v11.1.0
  images/build/debian-base/variants.yaml
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/XS

#1480 images: Build debian-iptables:v12.1.2
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1481 Version markers fix
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1482 kube-cross: Build v1.15.0-rc.2-1 image
  dependencies.yaml
  images/build/cross/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/S

#1483 base-images: Build debian-hyperkube-base:v1.1.3
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1484 k8s-cloud-builder: Build on kube-cross:v1.15.0-rc.2-1
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1485 Use logrus instead of stdOutWriter for verbose commands
  pkg/command/command.go
  pkg/command/command_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1487 kube-cross: Build v1.15.0-1 image
  dependencies.yaml
  images/build/cross/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/S

#1490 k8s-cloud-builder: Build on kube-cross:v1.15.0-1
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1491 HACK/REMOVE: Temporarily comment out the GCS target check
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/S

#1495 Rename release-notes --github-org/repo flags
  cmd/release-notes/README.md
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/S

#1488 Remove unused mailto flag from anago
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1496 images: Use OS codenames to construct clearer versions for Debian images
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/buster/Dockerfile
  images/build/debian-base/buster/Dockerfile.build
  images/build/debian-base/buster/clean-install
  images/build/debian-base/buster/excludes
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-base/stretch/Dockerfile
  images/build/debian-base/stretch/Dockerfile.build
  images/build/debian-base/stretch/clean-install
  images/build/debian-base/stretch/excludes
  images/build/debian-base/variants.yaml
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/buster/Dockerfile
  images/build/debian-iptables/buster/iptables-wrapper
  images/build/debian-iptables/cloudbuild.yaml
  images/build/debian-iptables/stretch/Dockerfile
  images/build/debian-iptables/stretch/iptables-wrapper
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, kind/design, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1498 images: Migrate go-runner image building to k/release
  BUILD.bazel
  dependencies.yaml
  images/build/go-runner/BUILD.bazel
  images/build/go-runner/Dockerfile
  images/build/go-runner/Makefile
  images/build/go-runner/OWNERS
  images/build/go-runner/README.md
  images/build/go-runner/cloudbuild.yaml
  images/build/go-runner/go-runner.go
  images/build/go-runner/go.mod
  images/build/go-runner/go.sum
  images/build/go-runner/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1505 Fix dependency report generation for new minor releases
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/regression, lgtm, priority/critical-urgent, release-note, sig/release, size/XS

#1508 Fix note exclusion regex to be more strict
  pkg/notes/notes.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1507 Skip release-notes dependency report if start and end SHA are equal
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1509 images: Build debian-base:buster-v1.1.4
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1510 images: Build debian-iptables:buster-v1.2.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S
