Repository kubernetes/release, pull requests merged in 2020-07, with the labels that each got.

#1385 push-build: Support uploading multiple version markers
  gcb/build/cloudbuild.yaml
  gcb/build/variants.yaml
  lib/releaselib.sh
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, sig/testing, size/M

#1386 push-build: Support pushing cross builds to a /cross subdirectory
  anago
  lib/releaselib.sh
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, priority/critical-urgent, release-note, sig/release, size/S

#1387 push-build: Prevent cross build and amd64 version marker collisions
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1389 push-build: Support pushing fast builds to a /fast subdirectory
  lib/releaselib.sh
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1390 Add command.Verbose() method
  pkg/command/command.go
  pkg/command/command_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1391 Add `Commands` structure to command package
  pkg/command/command.go
  pkg/command/command_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1392 Cleanup log package
  pkg/log/log.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1398 anago: set verbose to git push
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1399 anago: remove verbose flag from git push command
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1400 gcb: Update GitHub token
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note-none, sig/release, size/XS

#1401 Add saschagrunert and alejandrox1 as SIG Release admins
  OWNERS_ALIASES
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1405 krel/ff: dont restore the branch if the cleanup flag is set
  cmd/krel/cmd/ff.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1406 kube-cross: Build v1.14.5-1 and v1.13.13-1 images
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, size/S

#1407 k8s-cloud-builder: Build on kube-cross:v1.14.5-1 and v1.13.13-1
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, sig/release, size/XS

#1402 Add saschagrunert and alejandrox1 to SECURITY_CONTACTS
  SECURITY_CONTACTS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1409 Make release notes logging more verbose
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1404 kube-cross: overwrite user and group for etcd source
  images/build/cross/Dockerfile
  images/build/cross/variants.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, size/XS

#1411 kube-cross: Build v1.14.6-1
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note, size/XS

#1413 Correctly populate err for krel release-notes
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1412 Improve release-notes --format help output
  cmd/release-notes/main.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/XS

#1415 kube-cross: Build v1.13.14-1 and v1.15.0-beta.1-canary-1 images
  images/build/cross/Makefile
  images/build/cross/cloudbuild.yaml
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/S

#1417 k8s-cloud-builder: Build on kube-cross:v1.14.6-1 and v1.13.14-1
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1416 changelog: remove changelog files from other releases when we cut the first official release
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1420 kube-cross: Build v1.15.0-beta.1-1 image
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/XS

#1419 Split go template and format in options
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1230 [VDF] anago: Publish container images on K8s Infra (k8s-staging-kubernetes) - take two
  anago
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1422 Release-notes bugfix + add template option validation
  cmd/release-notes/main.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1423 Change ReleaseNotes to an own struct
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/main.go
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/L

#1424 lib/release: Remove GCRIO_PATH_PROD_PUSH logic
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/S

#1425 hack/anago: temporary remove the tag check
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, sig/release, size/S

#1426 anago: fix hack error
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1428 HACK: short circuit anago past 1.19.0-rc2 failure
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1429 revert 1.19.0-rc2 Anago hacks
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1432 Unlist release notes during processing
  pkg/notes/notes.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1434 Apply minor fixes to the release-notes tool
  README.md
  cmd/release-notes/main.go
  pkg/notes/notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1435 google build admins: take ownership of rapture
  OWNERS_ALIASES
  hack/rapture/OWNERS
  hack/rapture/README.md
  hack/rapture/k8s-rapture.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1436 Add Signed-off-by line to git.UserCommit
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1437 kube-cross: Build v1.15.0-rc.1-1 image
  images/build/cross/variants.yaml
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/XS

#1439 k8s-cloud-builder: Build on kube-cross:v1.15.0-rc.1-1 and add canary
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1373 Release notes mappings libraries and in krel release-notes
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/main.go
  docs/release-notes-maps.md
  pkg/gcp/gcs/gcs.go
  pkg/github/github.go
  pkg/notes/BUILD.bazel
  pkg/notes/document/BUILD.bazel
  pkg/notes/document/document.go
  pkg/notes/maps/testdata/cve-2020-8555.yaml
  pkg/notes/maps/testdata/fullmap.yaml
  pkg/notes/notes.go
  pkg/notes/notes_map.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#1443 Add repo SECURITY.md
  SECURITY.md
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, release-note-none, sig/release, size/S

#1442 Migration of doc updates to rapture release
  hack/rapture/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1444 push-build: Fix directory listing for fast builds
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/release, sig/testing, size/S

#1394 Remove --build-at-head flag from anago and releaselib
  anago
  find_green_build
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/M

#1448 lib/release: Only publish ci/latest-fast marker during CI fast builds
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1388 gcbmgr: add releases numbers tags to the cloudbuild
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/L

#1395 Finish release.SetBuildVersion() implementation
  .golangci.yml
  pkg/release/build_version.go
  pkg/release/build_version_test.go
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_gcp_client.go
  pkg/release/releasefakes/fake_http_client.go
  pkg/release/releasefakes/fake_job_cache_client.go
  pkg/release/releasefakes/fake_test_grid_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL
