Repository kubernetes/release, pull requests merged in 2020-03, with the labels that each got.

#1107 Add dedicated types for Kind and Notes
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/BUILD.bazel
  cmd/release-notes/main.go
  pkg/notes/BUILD.bazel
  pkg/notes/document/BUILD.bazel
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/notes.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1129 Remove branchff script
  README.md
  anago
  branchff
  docs/branching.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1136 Add dedicated GitHub package
  BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  pkg/git/BUILD.bazel
  pkg/git/git.go
  pkg/github/BUILD.bazel
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/github/githubfakes/BUILD.bazel
  pkg/github/githubfakes/fake_client.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XL

#1137 Change CHANGELOG url back to master branch
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1142 Update go dependencies
  cmd/krel/cmd/root_test.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1141 images: Update k8s-cloud-builder to use the new kube-cross location
  anago
  gcb/build/cloudbuild.yaml
  gcb/patch-announce/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  images/k8s-cloud-builder/Dockerfile
  lib/releaselib.sh
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1143 [krel] changelog: Include CHANGELOG/README.md in master commit logic
  anago
  cmd/krel/cmd/changelog.go
  lib/gitlib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/release, size/M

#1145 Refactor kubepkg.fetchReleases into github.Releases()
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/github/githubfakes/fake_client.go
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkg.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1008 Add support for using arbitrary Go template when generating markdown.
  .golangci.yml
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  go.mod
  go.sum
  pkg/notes/document/BUILD.bazel
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/document/testdata/document.md.golden
  pkg/notes/internal/BUILD.bazel
  pkg/notes/internal/template.go
  pkg/notes/options/BUILD.bazel
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, sig/release, size/XL

#1146 images: Add skopeo@v0.1.41 to k8s-cloud-builder
  images/k8s-cloud-builder/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1147 Reduce cyclomatic complexity of ValidateAndFinish()
  .golangci.yml
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1151 Make AddTagPrefix idempotent
  pkg/util/BUILD.bazel
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1152 Make PackagesAvailable() more universal
  pkg/util/common.go
  pkg/util/common_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1149 Refactor CreateDownloadsTable to use fetchMetadata
  cmd/release-notes/BUILD.bazel
  cmd/release-notes/main.go
  pkg/notes/document/BUILD.bazel
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1158 Stop spaming rendered documents with empty downloads info
  cmd/krel/cmd/changelog_data_test.go
  pkg/notes/document/document.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, ok-to-test, release-note-none, sig/release, size/M

#1155 Add changelog minor release integration test
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1159 Render notes with no kind information as normal Changes by Kind
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/document/testdata/document.md.golden
Labels: approved, area/release-eng, cncf-cla: yes, kind/design, lgtm, needs-priority, ok-to-test, release-note-action-required, sig/release, size/M

#1160 [krel] gcbmgr: Disable BUILD_AT_HEAD substitution and properly set GIT_TAG
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  pkg/gcp/build/BUILD.bazel
  pkg/gcp/build/build.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/release

#1162 gcp: Update GCB and releaselib to use new k8s-staging-releng project
  gcb/build/cloudbuild.yaml
  gcb/build/variants.yaml
  gcb/patch-announce/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, needs-priority, release-note, sig/release, size/S

#1156 Add downloads table to minor release CHANGELOG
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_data_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1157 Add dedicated HTTP package to be testable
  BUILD.bazel
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  pkg/http/BUILD.bazel
  pkg/http/http.go
  pkg/http/http_test.go
  pkg/release/BUILD.bazel
  pkg/release/release.go
  pkg/util/common.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1163 gcb: Move KMS keys to k8s-releng-prod GCP project
  gcb/patch-announce/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1167 Fix gcb build variable substitution
  gcb/build/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1165 Refactor release package kube version retrieval
  cmd/krel/cmd/gcbmgr.go
  pkg/git/git.go
  pkg/kubepkg/kubepkg.go
  pkg/release/BUILD.bazel
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/release/version.go
  pkg/release/version_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#1168 Fix HTML rendering by using goldmark
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XXL

#1153 Add verify-go make target
  .gitignore
  Makefile
  hack/verify-golangci-lint.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/M

#1166 Use markdown headers for pull request and issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/M

#1169 Add release package unit tests
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1164 Deprecate shell-based gcbmgr and add usage documentation for Go-based 'krel gcbmgr'
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  docs/krel/gcbmgr.md
  gcbmgr
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, kind/documentation, lgtm, priority/important-soon, release-note, sig/release, size/L

#1174 Fix failing build-packages-rpms test in kubepkg
  pkg/kubepkg/kubepkg.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/S

#1177 Make github package client token capable
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/patch-announce.go
  cmd/krel/cmd/release_notes.go
  pkg/github/BUILD.bazel
  pkg/github/github.go
  pkg/notes/BUILD.bazel
  pkg/notes/notes_test.go
  pkg/notes/options/BUILD.bazel
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  pkg/patch/internal/BUILD.bazel
  pkg/patch/internal/release_notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#1178 Merge notes client and github client
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/main.go
  pkg/github/BUILD.bazel
  pkg/github/github.go
  pkg/github/githubfakes/fake_client.go
  pkg/github/internal/BUILD.bazel
  pkg/github/internal/retry.go
  pkg/github/internal/retry_test.go
  pkg/github/record.go
  pkg/github/replay.go
  pkg/notes/BUILD.bazel
  pkg/notes/client/BUILD.bazel
  pkg/notes/client/client.go
  pkg/notes/client/clientfakes/BUILD.bazel
  pkg/notes/client/clientfakes/fake_client.go
  pkg/notes/document/BUILD.bazel
  pkg/notes/internal/BUILD.bazel
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_test.go
  pkg/notes/options/BUILD.bazel
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XXL

#1148 Follow up to PR#1008: Lazy loading of format spec and Sorting Notes
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/release_notes.go
  cmd/release-notes/README.md
  cmd/release-notes/main.go
  go.mod
  go.sum
  pkg/notes/document/BUILD.bazel
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/document/template.go
  pkg/notes/document/testdata/document.md.golden
  pkg/notes/document/testdata/document_without_downloads.md.golden
  pkg/notes/internal/BUILD.bazel
  pkg/notes/options/BUILD.bazel
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, ok-to-test, release-note-action-required, sig/release, size/XL

#1181 typos: fix small typos
  cmd/krel/cmd/testdata/changelog-v1.16.3/GetPullRequest-8.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-102.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-11.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-139.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-18.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-9.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListCommits-0.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListCommits-1.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListCommits-3.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-11.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-117.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-138.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-18.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-37.json
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1182 krel changelog: remove other CHANGELOG-*.md only on first RC
  cmd/krel/cmd/changelog.go
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
  cmd/krel/cmd/testdata/changelog-v1.16.0-rc.1/GetCommit-0.json
  cmd/krel/cmd/testdata/changelog-v1.16.0-rc.1/GetCommit-1.json
  cmd/krel/cmd/testdata/changelog-v1.16.0-rc.1/ListCommits-0.json
  cmd/krel/cmd/testdata/changelog-v1.16.0-rc.1/ListPullRequestsWithCommit-0.json
  cmd/krel/cmd/testdata/changelog-v1.16.0-rc.1/ListPullRequestsWithCommit-1.json
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/L

#1187 Fix `github.LatestGitHubTagsPerBranch()` to list all branches
  pkg/github/github.go
  pkg/github/github_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/M

#1189 gcbmr: missing replace the release branch in the confirmation msg
  cmd/krel/cmd/gcbmgr.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1188 Fix building deb packages in kubepkg
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkg_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1196 Add further kinds to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1197 Use util.EnvDefault for GetTool{Org,Repo,Branch}
  pkg/release/release.go
  pkg/release/release_test.go
  pkg/util/env.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1172 Configure releng GCB jobs to use new staging project and add VDF TODOs
  cmd/krel/cmd/gcbmgr.go
  cmd/patch-announce/BUILD.bazel
  cmd/patch-announce/main.go
  docs/krel/gcbmgr.md
  lib/releaselib.sh
  pkg/release/release.go
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1140 images: Move kube-cross image building to k/release
  OWNERS_ALIASES
  images/build/OWNERS
  images/build/cross/Dockerfile
  images/build/cross/Makefile
  images/build/cross/VERSION
  images/build/cross/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1200 kube-cross: Update to go1.13.9
  images/build/cross/Dockerfile
  images/build/cross/VERSION
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/XS

#1183 Add docs to options package
  cmd/krel/cmd/changelog.go
  cmd/release-notes/main.go
  pkg/notes/options/options.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/L

#1191 Make unnecessary public functions private
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1193 deps: update dependencies - Testgrid
  go.mod
  go.sum
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/L

#1170 images/releng-ci-bazel: Add jq, bsdmainutils and google-cloud-sdk
  images/releng-ci-bazel/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1190 Increase verbosity of krel changelog
  cmd/krel/cmd/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1198 Add command.Addwriter() support
  pkg/command/command.go
  pkg/command/command_test.go
  pkg/gcp/build/build.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1201 First compilation of krel documentation
  docs/krel/README.md
  docs/krel/changelog.md
  docs/krel/ff.md
  docs/krel/gcbmgr.md
  docs/krel/patch-announce.md
  docs/krel/push.md
  docs/krel/release-notes.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note, sig/release, size/L

#1202 kube-cross: Fix image pushing job failures
  images/build/cross/Makefile
  images/build/cross/VERSION
  images/build/cross/cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, needs-priority, release-note, size/M

#1194 gcbmgr: add list build jobs
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  go.mod
  go.sum
  pkg/gcp/build/BUILD.bazel
  pkg/gcp/build/build.go
  repos.bzl
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1185 Add options to generate and push the JSON version of the release notes
  cmd/krel/cmd/release_notes.go
  pkg/git/git.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1208 kube-cross: Update to go1.14.1
  images/build/cross/Dockerfile
  images/build/cross/VERSION
Labels: approved, area/dependency, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/XS

#1206 Fix releng-ci-bazel image build
  images/releng-ci-bazel/Dockerfile
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1205 Default to master branch in gcbmgr
  cmd/krel/cmd/gcbmgr.go
  docs/krel/gcbmgr.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1171 Enable krel gcbmgr package and binary checks
  cmd/krel/cmd/gcbmgr.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1210 testgrishot: remove canned_acl
  testgridshot
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1211 look for version in bazel-bin
  pkg/release/release.go
  pkg/release/release_test.go
  push-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/M

#1213 Make git.GetRepoURL infallible
  cmd/krel/cmd/release_notes.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/git/git_test.go
  pkg/release/release.go
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/M

#1209 Update k8s-cloud-builder to use kube-cross:v1.13.9-2
  gcb/build/cloudbuild.yaml
  gcb/patch-announce/cloudbuild.yaml
  images/k8s-cloud-builder/Dockerfile
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1215 Fix low performance on repo.Add()
  pkg/git/git.go
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/S

#1218 Fix changelog integration test for new alpha
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, sig/release, size/S

#1217 Set ReleaseVersion for generated notes
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/XS

#1214 Use testify require instead of assert
  pkg/git/BUILD.bazel
  pkg/git/git_test.go
  pkg/kubepkg/BUILD.bazel
  pkg/kubepkg/kubepkg_test.go
  pkg/release/BUILD.bazel
  pkg/release/release_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1219 Remove gcbmgr bash script
  README.md
  anago
  gcbmgr
  images/README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, needs-priority, release-note, sig/release, size/L

#1220 Make git.Describe more flexible
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/gcbmgr.go
  pkg/gcp/build/BUILD.bazel
  pkg/gcp/build/build.go
  pkg/git/BUILD.bazel
  pkg/git/describe.go
  pkg/git/describe_test.go
  pkg/git/git.go
  pkg/git/git_integration_test.go
  pkg/release/release.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/api-change, lgtm, needs-priority, release-note, sig/release, size/L

#1222 Fix some whitespace related formatting in docs/krel
  docs/krel/README.md
  docs/krel/changelog.md
  docs/krel/ff.md
  docs/krel/gcbmgr.md
  docs/krel/patch-announce.md
  docs/krel/push.md
  docs/krel/release-notes.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#1221 Add repo state check to gcbmgr
  cmd/krel/cmd/BUILD.bazel
  cmd/krel/cmd/cmdfakes/BUILD.bazel
  cmd/krel/cmd/cmdfakes/fake_repository.go
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
  pkg/gcp/build/build.go
  pkg/git/git.go
  pkg/release/BUILD.bazel
  pkg/release/release.go
  pkg/release/releasefakes/BUILD.bazel
  pkg/release/releasefakes/fake_repository.go
  pkg/release/repository.go
  pkg/release/repository_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1223 lib/release: Use regex to prevent ACL changes on K8s Infra GCS buckets
  lib/releaselib.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1224 anago: Fix '--build-version' flag in anago tooltip for 'krel gcbmgr'
  anago
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#1225 Pass options on RunGcbmgr
  cmd/krel/cmd/gcbmgr.go
  cmd/krel/cmd/gcbmgr_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L
