Repository kubernetes/release, pull requests merged in 2021-11, with the labels that each got.

#2303 update cosign to v1.3.0
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2305 [go] Build go1.17.3 and go1.16.10 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, priority/important-soon, sig/release, area/release-eng, area/dependency

#2306 k8s-cloud-builder/k8s-ci-builder: Build image using go1.17.3
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2301 add go-runner to debian-iptables image
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/buster/Dockerfile
  images/build/debian-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2310 debian-iptables: add go-runner to bullseye image
  dependencies.yaml
  images/build/debian-iptables/bullseye/Dockerfile
  images/build/debian-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2311 k8s-cloud-builder/k8s-ci-builder: Build image using go1.16.10
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2309 Add a new ci-reporter tool to generate weekly CI Signal Reports
  OWNERS_ALIASES
  cmd/ci-reporter/OWNERS
  cmd/ci-reporter/README.md
  cmd/ci-reporter/report.go
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, priority/critical-urgent, sig/release, kind/documentation, area/release-eng

#2315 cosign: update cosign to 1.3.1
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2314 Refactor new ci-signal tool
  cmd/ci-reporter/README.md
  cmd/ci-reporter/report.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note, sig/release, kind/cleanup, tide/merge-method-squash, area/release-eng, needs-priority

#2300 Provenance attesattion for artifacts
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/anago/release_test.go
  pkg/provenance/provenancefakes/fake_statement_implementation.go
  pkg/provenance/statement.go
  pkg/release/provenance.go
  pkg/spdx/document.go
  pkg/spdx/object.go
  pkg/spdx/parser.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2320 Minor improvements to krel promote-images
  cmd/krel/cmd/promote-images.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, priority/important-soon, sig/release, kind/documentation, area/release-eng

#2322 Remove vulndash
  .github/ISSUE_TEMPLATE/dep-golang.md
  cmd/vulndash/Dockerfile
  cmd/vulndash/Makefile
  cmd/vulndash/OWNERS
  cmd/vulndash/cloudbuild.yaml
  cmd/vulndash/cmd/root.go
  cmd/vulndash/dashboard.html
  cmd/vulndash/dashboard.js
  cmd/vulndash/main.go
  cmd/vulndash/variants.yaml
  dependencies.yaml
  go.mod
  pkg/vulndash/OWNERS
  pkg/vulndash/adapter/adapter.go
  pkg/vulndash/adapter/adapter_test.go
  pkg/vulndash/adapter/types.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note, sig/release, kind/cleanup, area/release-eng, kind/deprecation, needs-priority, area/release-eng/security

#2323 images: Default to `bullesye` variants and cleanup EOL components
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/legacy/Dockerfile
  images/build/cross/variants.yaml
  images/build/debian-base/Makefile
  images/build/debian-iptables/Makefile
  images/build/go-runner/Makefile
  images/build/setcap/Makefile
  images/k8s-cloud-builder/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, approved, kind/cleanup, area/dependency

#2324 relnotes: Sleep when hitting the secondary GH limit
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note, priority/critical-urgent, kind/failing-test, sig/release, kind/flake, area/release-eng

#2325 remove dh-systemd package which no longer exists
  Dockerfile-kubepkg
  cmd/kubepkg/templates/latest/deb/kubelet/debian/control
  packages/deb/Dockerfile
  packages/deb/bionic/kubelet/debian/control
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2316 Clean up ci-signal report and adding cobra
  cmd/ci-reporter/README.md
  cmd/ci-reporter/cmd/github.go
  cmd/ci-reporter/cmd/root.go
  cmd/ci-reporter/cmd/testgrid.go
  cmd/ci-reporter/main.go
  cmd/ci-reporter/report.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, kind/feature, release-note, sig/release, kind/cleanup, tide/merge-method-squash, area/release-eng, needs-priority

#2326 krel: Move `promote-images` subcommand to sigs.k8s.io/promo-tools
  cmd/krel/cmd/promote-images.go
  cmd/krel/cmd/release_notes.go
  docs/krel/README.md
  go.mod
  go.sum
  pkg/release/release.go
  pkg/release/release_test.go
Labels: lgtm, cncf-cla: yes, size/XL, approved, release-note, sig/release, kind/cleanup, area/release-eng, area/dependency, kind/deprecation, needs-priority

#2329 Fix several typos/nits in comments
  pkg/spdx/builder.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#2330 Migrate `bom` utility to sigs.k8s.io/bom
  README.md
  cmd/bom/README.md
  cmd/bom/cmd/document.go
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
  cmd/bom/main.go
  compile-release-tools
  docs/bom/418528.svg
  docs/bom/README.md
  docs/bom/cast.svg
  docs/bom/create-a-bill-of-materials.md
  docs/bom/etcd-v3.4.16.spdx
  docs/bom/generate.md
  go.mod
  go.sum
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/stage.go
  pkg/anago/stage_test.go
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/license_unit_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
  pkg/provenance/predicate.go
  pkg/provenance/predicate_test.go
  pkg/provenance/predicate_unit_test.go
  pkg/provenance/provenance.go
  pkg/provenance/provenance_unit_test.go
  pkg/provenance/provenancefakes/fake_predicate_implementation.go
  pkg/provenance/provenancefakes/fake_statement_implementation.go
  pkg/provenance/statement.go
  pkg/provenance/statement_test.go
  pkg/provenance/statement_unit_test.go
  pkg/provenance/testdata/k8s-1.23.0-alpha.4-provenance.json
  pkg/release/provenance.go
  pkg/release/workspace.go
  pkg/spdx/builder.go
  pkg/spdx/builder_unit_test.go
  pkg/spdx/document.go
  pkg/spdx/file.go
  pkg/spdx/gomod.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_distroless.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/object.go
  pkg/spdx/package.go
  pkg/spdx/parser.go
  pkg/spdx/relationship.go
  pkg/spdx/spdx.go
  pkg/spdx/spdx_test.go
  pkg/spdx/spdx_unit_test.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note, sig/release, kind/cleanup, area/release-eng, kind/deprecation, needs-priority

#2331 Simplify `OWNERS` and federate review obligations
  OWNERS
  OWNERS_ALIASES
  cmd/krel/OWNERS
  cmd/release-notes/OWNERS
  pkg/OWNERS
  pkg/notes/OWNERS
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2335 Changelog: (re)Add links to markdown output
  cmd/krel/cmd/changelog_data_test.go
  pkg/changelog/changelog.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/bug, release-note, priority/important-soon, sig/release, area/release-eng
