Repository kubernetes/release, pull requests merged in 2021-08, with the labels that each got.

#2186 Update SBOM URIs/Namespaces to final location
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note, sig/release, size/XS

#2188 [go1.17] Build images for go1.17rc2
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#2189 debian-base: Build buster-v1.9.0 image
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#2190 k8s-cloud-builder: Build v1.17.0-rc.2-1 image
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#2192 images: Build debian-iptables / setcap from debian-base:buster-v1.9.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
  images/build/setcap/Makefile
  images/build/setcap/variants.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#2194 Generate TOC after dependencies
  pkg/changelog/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/release, size/S

#2197 [go] Build go1.16.7 and go1.15.15 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, priority/important-soon, sig/release, area/release-eng, area/dependency, area/release-eng/security

#2198 k8s-cloud-builder/k8s-ci-builder: Build image using go1.16.7
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, priority/important-soon, sig/release, area/release-eng

#2200 k8s-cloud-builder/k8s-ci-builder: Build image using go1.15.15
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, priority/important-soon, sig/release, area/release-eng

#2201 gh/issues: update dep-go issue template to add staging/publishing bot rules step
  .github/ISSUE_TEMPLATE/dep-golang.md
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#2193 Don't generate dependency report for release notes draft
  cmd/krel/cmd/release_notes.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note, sig/release, kind/api-change, area/release-eng, needs-priority

#2206 SPDX: Correctly form layer references for single images
  pkg/spdx/implementation.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2208 Update schedule-builder docs
  cmd/schedule-builder/README.md
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#2209 debian-base: Build bullseye-v1.0.0 images
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/bullseye/Dockerfile
  images/build/debian-base/bullseye/Dockerfile.build
  images/build/debian-base/bullseye/clean-install
  images/build/debian-base/bullseye/excludes
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority, area/release-eng/security

#2213 bom: fix panic when LICENSE file is not found
  pkg/spdx/implementation.go
  pkg/spdx/spdx.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, priority/important-soon, sig/release, ok-to-test, area/release-eng

#2216 Stop uploading .deb packages to scratch bucket
  packages/deb/jenkins.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#2217 Stop updating /debian/latest marker in scratch bucket
  packages/deb/jenkins.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#2218 debian-builder: use golang:1.16.7-buster as the base image
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2214 OWNERS cleanup
  OWNERS_ALIASES
  SECURITY_CONTACTS
  cmd/vulndash/OWNERS
  images/OWNERS
  images/artifact-promoter/Makefile.artifact-promoter
  images/artifact-promoter/OWNERS
  images/build/OWNERS
  images/build/debian-base/OWNERS
  images/build/debian-iptables/OWNERS
  images/build/go-runner/OWNERS
  pkg/vulndash/OWNERS
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority, area/release-eng/security

#2219 un-emeritus BenTheElder per https://github.com/kubernetes/release/pul…
  images/build/OWNERS
  images/build/debian-base/OWNERS
  images/build/debian-iptables/OWNERS
  images/build/go-runner/OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2221 Clean up extra spaces
  cmd/bom/cmd/root.go
  cmd/kpromo/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority, area/artifacts

#2211 [go1.17] Build images for go1.17
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  cloudbuild-kubepkg.yaml
  cmd/vulndash/Dockerfile
  cmd/vulndash/Makefile
  cmd/vulndash/cloudbuild.yaml
  cmd/vulndash/variants.yaml
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/canary/Dockerfile
  images/build/cross/cloudbuild.yaml
  images/build/cross/default/Dockerfile
  images/build/cross/variants.yaml
  images/build/go-runner/Dockerfile
  images/build/go-runner/Makefile
  images/build/go-runner/cloudbuild.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/Dockerfile
  images/releng/ci/cloudbuild.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XL, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2222 k8s-cloud-builder: Update to v1.23.0-go1.17-buster.0
  dependencies.yaml
  images/k8s-cloud-builder/cloudbuild.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2224 k8s-ci-builder: Sync with cleanups in krte
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/ci-failures
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/create_bazel_cache_rcs.sh
  images/releng/k8s-ci-builder/install-bazel.sh
  images/releng/k8s-ci-builder/variants.yaml
  images/releng/k8s-ci-builder/wrapper.sh
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2223 [go1.17] Default to go1.17
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  go.mod
  images/build/cross/Makefile
  images/build/go-runner/Makefile
  images/build/go-runner/go.mod
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  packages/deb/Dockerfile
  packages/deb/go.mod
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, kind/cleanup, area/release-eng, area/dependency, needs-priority

#2228 Lintlintlint
  .golangci.yml
  cmd/krel/cmd/announce_build.go
  cmd/krel/cmd/changelog_test.go
  cmd/krel/cmd/release_notes.go
  cmd/krel/cmd/testgrid.go
  dependencies.yaml
  hack/verify-golangci-lint.sh
  pkg/anago/anago.go
  pkg/anago/anago_test.go
  pkg/announce/github_page.go
  pkg/api/files/validation.go
  pkg/binary/binary_unit_test.go
  pkg/binary/mach-o.go
  pkg/binary/windows.go
  pkg/changelog/changelog.go
  pkg/cve/impl.go
  pkg/filepromoter/file.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/filepromoter/manifest.go
  pkg/git/git_integration_test.go
  pkg/git/git_test.go
  pkg/github/github_test.go
  pkg/github/record.go
  pkg/kubepkg/kubepkg_test.go
  pkg/notes/document/document_test.go
  pkg/notes/notes_test.go
  pkg/notes/options/options.go
  pkg/notes/options/options_test.go
  pkg/promobot/hash.go
  pkg/promobot/hash_test.go
  pkg/promobot/promotefiles.go
  pkg/release/release_test.go
  pkg/spdx/relationship.go
  pkg/spdx/spdx_unit_test.go
  pkg/vulndash/adapter/adapter.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority, area/artifacts

#2229 Update `cosign` to v1.1.0
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2232 Migrate `pkg/object` and `pkg/gcp/gcp.go` to sigs.k8s.io/release-sdk
  cmd/gh2gcs/cmd/root.go
  cmd/krel/cmd/testgrid.go
  go.mod
  go.sum
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/api/files/validation.go
  pkg/build/build.go
  pkg/changelog/impl.go
  pkg/cve/client.go
  pkg/cve/impl.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/gcp/auth/auth.go
  pkg/gcp/build/build.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcp.go
  pkg/gh2gcs/gh2gcs.go
  pkg/notes/notes_map.go
  pkg/object/gcs.go
  pkg/object/gcs_test.go
  pkg/object/objectfakes/fake_store.go
  pkg/object/store.go
  pkg/release/archive.go
  pkg/release/archive_unit_test.go
  pkg/release/prerequisites.go
  pkg/release/publish.go
  pkg/release/release.go
  pkg/release/workspace.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority, area/artifacts
