Repository kubernetes/release, pull requests merged in 2021-01, with the labels that each got.

#1835 images: Build debian-base:buster-v1.3.0
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, ok-to-test, release-note, sig/release, size/XS

#1828 Generate full json release notes on first minor
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1843 Make staging of extra files optional
  pkg/build/build.go
  pkg/build/push.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1845 Update go-github to v33.0.0
  go.mod
  go.sum
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/github/githubfakes/fake_client.go
  pkg/github/internal/retry.go
  pkg/github/internal/retry_test.go
  pkg/github/record.go
  pkg/github/replay.go
  pkg/kubepkg/kubepkg.go
  pkg/kubepkg/kubepkgfakes/fake_impl.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1839 Fix non-amd64 arch config for debian images
  images/build/debian-base/Makefile
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-iptables/Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, priority/critical-urgent, release-note, sig/release, size/S

#1844 dependencies: update several dependecies
  go.mod
  go.sum
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/M

#1832 Update SECURITY_CONTACTS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1847 vulndash: add filter to get vulnerabilities for a specific registry hostname
  cmd/vulndash/Makefile
  cmd/vulndash/cmd/root.go
  cmd/vulndash/variants.yaml
  dependencies.yaml
  pkg/vulndash/adapter/adapter.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/M

#1846 Add do_not_publish map flag to remove release note from final document
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/release_notes.go
  pkg/notes/document/document.go
  pkg/notes/notes.go
  pkg/notes/notes_map.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/M

#1849 Revert "Merge pull request #1839 from sozercan/fix-arch"
  images/build/debian-base/Makefile
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-iptables/Makefile
Labels: approved, cncf-cla: yes, kind/bug, kind/regression, lgtm, priority/critical-urgent, release-note-none, sig/release, size/S

#1852 Add wait and retry after creating the GitHub release page
  pkg/announce/github_page.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1853 Add support for arm64 to kube-cross image
  images/build/cross/Dockerfile
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, size/M

#1854 vulndash: improve vulndash html page
  cmd/vulndash/Makefile
  cmd/vulndash/dashboard.html
  cmd/vulndash/dashboard.js
  cmd/vulndash/variants.yaml
  dependencies.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1858 cross: increase gcb job timeout to 30 min
  images/build/cross/cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, size/XS

#1859 images: Build debian-iptables:buster-v1.4.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, sig/release, size/S

#1861 images: Build debian-hyperkube-base:buster-v1.3.0
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1856 Binary package: Base module for binary analysis
  pkg/binary/binary.go
  pkg/binary/binary_test.go
  pkg/binary/binaryfakes/fake_binary_implementation.go
  pkg/binary/elf.go
  pkg/binary/header.go
  pkg/binary/mach-o.go
  pkg/binary/windows.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1863 Add verify-build step to make target
  Makefile
  hack/verify-build.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/M

#1865 images: fix Archs expansion in makefile
  images/Makefile.common-image
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/release, size/XS

#1866 kube-cross: bump image of kube-cross
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1867 kube-cross: set gcb timeout to 1h
  images/build/cross/cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, size/XS

#1864 Switch to buildx for building multi architecture images
  cmd/vulndash/cloudbuild.yaml
  dependencies.yaml
  images/build/cross/cloudbuild.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-base/variants.yaml
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-hyperkube-base/cloudbuild.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/cloudbuild.yaml
  images/build/go-runner/cloudbuild.yaml
  images/releng/k8s-ci-builder/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1868 Fix GCR authentication for base images
  images/build/debian-base/cloudbuild.yaml
  images/build/debian-hyperkube-base/cloudbuild.yaml
  images/build/debian-iptables/cloudbuild.yaml
Labels: approved, cncf-cla: yes, kind/bug, kind/regression, lgtm, needs-priority, release-note-none, sig/release, size/S

#1871 go-runner: bump image version
  dependencies.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/cloudbuild.yaml
  images/build/go-runner/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, sig/release, size/XS

#1870 Fix docker buildx image builds
  hack/verify-shellcheck.sh
  images/build/debian-base/Makefile
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-iptables/Makefile
  third_party/multiarch/qemu-user-static/LICENSE
  third_party/multiarch/qemu-user-static/README.kubernetes
  third_party/multiarch/qemu-user-static/register/qemu-binfmt-conf.sh
  third_party/multiarch/qemu-user-static/register/register.sh
Labels: approved, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, release-note-none, sig/release, size/L

#1874 Add k8s.io/release/pkg/license package
  go.mod
  go.sum
  pkg/license/download.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/license_unit_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
  pkg/license/spdx.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#1875 Move shared hash functions into own package
  pkg/announce/github_page.go
  pkg/filepromoter/file.go
  pkg/hash/hash.go
  pkg/hash/hash_test.go
  pkg/notes/document/document.go
  pkg/promobot/hash.go
  pkg/release/release.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#1872 Remove stretch based debian images
  images/build/debian-base/stretch/Dockerfile
  images/build/debian-base/stretch/Dockerfile.build
  images/build/debian-base/stretch/clean-install
  images/build/debian-base/stretch/excludes
  images/build/debian-base/variants.yaml
  images/build/debian-iptables/stretch/Dockerfile
  images/build/debian-iptables/variants.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, size/L

#1876 Update k8s-cloud-builder to v1.15.7-2 and k8s-ci-builder to 1.15.7
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/S

#1877 Update debian-iptables to v1.5.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#1878 Update debian-hyperkube-base to v1.4.0
  dependencies.yaml
  images/build/debian-hyperkube-base/Makefile
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#1879 Use MarshalIndent for JSON release notes output
  cmd/krel/cmd/release_notes.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/XS

#1827 Always switch to specified commit when tagging main branch
  pkg/anago/stage.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/S

#1881 Cleanup buildx builder after its usage
  images/build/debian-base/Makefile
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-iptables/Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#1882 [go1.16] Build go1.16rc1 images
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M
