Repository kubernetes/release, pull requests merged in 2021-05, with the labels that each got.

#2027 Fix expected to actual order for git tests
  pkg/git/git_integration_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/L

#2030 Fix gcs.PathExists() bug
  pkg/object/gcs.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/release, size/S

#2028 Drop krel cve write command
  cmd/krel/cmd/cve.go
  pkg/cve/client.go
  pkg/cve/cve.go
  pkg/cve/impl.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/release, size/L

#2031 Enable dependabot updates
  .github/dependabot.yml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS

#2042 Dependency updates
  .github/dependabot.yml
  cmd/krel/cmd/testgrid.go
  go.mod
  go.sum
  pkg/cip/cli/audit.go
Labels: approved, area/artifacts, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#1922 krel release-notes publishes to release-notes/ dir
  cmd/krel/cmd/changelog_data_test.go
  cmd/krel/cmd/changelog_test.go
  cmd/krel/cmd/release_notes.go
  pkg/changelog/changelog.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, release-note, sig/release, size/XXL

#2052 deps: Update sigs.k8s.io/release-utils to v0.2.1
  go.mod
  go.sum
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#2053 OWNERS updates
  OWNERS_ALIASES
  images/build/OWNERS
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#2054 Update `cosign` image to v0.4.0
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note-none, sig/release, size/XS

#2056 Fix list manipulation of release notes
  cmd/krel/cmd/changelog_data_test.go
  pkg/notes/notes.go
  pkg/notes/notes_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, sig/release, size/M

#2059 [go] Build go1.16.4 and go1.15.12 images
  cmd/vulndash/Makefile
  cmd/vulndash/variants.yaml
  dependencies.yaml
  hack/verify-dependencies.sh
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/cloudbuild.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#2061 [go1.16] Update kubernetes/kubernetes dependents to use go1.16.4
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
  packages/deb/Dockerfile
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#2062 pkg/release: Remove dependency on skopeo binary
  cmd/krel/cmd/ci_build.go
  cmd/krel/cmd/push.go
  dependencies.yaml
  docs/krel/push.md
  images/k8s-cloud-builder/Dockerfile
  images/k8s-cloud-builder/cloudbuild.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/cloudbuild.yaml
  images/releng/k8s-ci-builder/variants.yaml
  pkg/build/build.go
  pkg/release/images.go
  pkg/release/images_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note, sig/release, size/M

#1992 setcap: Build buster-v2.0.0 image
  dependencies.yaml
  images/build/setcap/Dockerfile
  images/build/setcap/Makefile
  images/build/setcap/variants.yaml
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#2063 [GO1.15] Update k8s-cloud-builder/k8s-ci-builder
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#2018 Remove hyperkube references
  dependencies.yaml
  images/build/debian-hyperkube-base/.gitignore
  images/build/debian-hyperkube-base/Dockerfile
  images/build/debian-hyperkube-base/Makefile
  images/build/debian-hyperkube-base/OWNERS
  images/build/debian-hyperkube-base/README.md
  images/build/debian-hyperkube-base/cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, needs-priority, release-note, sig/release, size/L

#2068 Update golangci-lint to v1.40.1 and fix lints
  .golangci.yml
  dependencies.yaml
  hack/verify-golangci-lint.sh
  pkg/binary/binary.go
  pkg/release/archive_unit_test.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/M

#2064 BOM: Feature complete SPDX and license packages
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/license/license_test.go
  pkg/license/licensefakes/fake_downloader_implementation.go
  pkg/license/licensefakes/fake_reader_implementation.go
  pkg/license/spdx.go
  pkg/spdx/builder.go
  pkg/spdx/document.go
  pkg/spdx/file.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_distroless.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#2069 SPDX package unit and integration tests
  pkg/spdx/spdx_test.go
  pkg/spdx/spdx_unit_test.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XL

#2066 bom: A utility to generate SPDX compliant Bills of Materials
  cmd/bom/cmd/generate.go
  cmd/bom/cmd/root.go
  cmd/bom/main.go
Labels: approved, area/release-eng, cncf-cla: yes, lgtm, needs-kind, needs-priority, release-note, sig/release, size/L

#2080 debian-base: Build buster-v1.7.0 image
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: approved, area/dependency, area/release-eng, area/release-eng/security, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XS

#2084 README.md: Add installation hint
  README.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, sig/release, size/XS

#2077 3 Major features for SPDX and bugfixes
  cmd/bom/cmd/generate.go
  go.mod
  pkg/license/catalog.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/license/license.go
  pkg/spdx/builder.go
  pkg/spdx/document.go
  pkg/spdx/file.go
  pkg/spdx/gomod.go
  pkg/spdx/imageanalyzer.go
  pkg/spdx/imageanalyzer_gorunner.go
  pkg/spdx/implementation.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/XXL

#2086 Add missing i386 crossbuild toolchain to kube-cross
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/default/Dockerfile
  images/build/cross/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, sig/release, size/S

#2089 releng-ci: Enable building multiple image variants
  dependencies.yaml
  images/releng/ci/ci-failures
  images/releng/ci/cloudbuild.yaml
  images/releng/ci/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, kind/failing-test, kind/feature, lgtm, needs-priority, release-note, sig/release, size/M

#2090 setcap image: symlink rm to /usr/sbin/rm
  images/build/setcap/Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, size/XS

#2097 pkg/cip: Revert os/io go1.16 changes
  pkg/cip/audit/auditor.go
  pkg/cip/dockerregistry/grow_manifest.go
  pkg/cip/dockerregistry/inventory.go
  pkg/cip/remotemanifest/git.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/regression, lgtm, needs-priority, release-note, sig/release, size/S

#2085 BOM: Include full list of transient go dependencies
  cmd/bom/cmd/generate.go
  pkg/license/download.go
  pkg/license/implementation.go
  pkg/spdx/builder.go
  pkg/spdx/gomod.go
  pkg/spdx/implementation.go
  pkg/spdx/package.go
  pkg/spdx/spdx.go
  pkg/spdx/spdxfakes/fake_spdx_implementation.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/bug, kind/cleanup, kind/design, kind/feature, lgtm, needs-priority, release-note, sig/release, size/L

#2091 debian-base: symlink rm to /usr/sbin/rm
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/buster/Dockerfile.build
  images/build/debian-base/variants.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/S

#2102 go.mod: Run `go mod tidy`
  go.mod
  go.sum
Labels: approved, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, sig/release, size/XS
