Repository kubernetes/release, pull requests merged in 2022-07, with the labels that each got.

#2597 debian-base: Update dependents to use bullseye-v1.4.0
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
  images/build/setcap/Makefile
  images/build/setcap/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, ok-to-test, area/release-eng, needs-priority

#2502 Create distroless iptables image
  OWNERS_ALIASES
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/OWNERS
  images/build/distroless-iptables/README.md
  images/build/distroless-iptables/cloudbuild.yaml
  images/build/distroless-iptables/distroless/Dockerfile
  images/build/distroless-iptables/distroless/clean-distroless.sh
  images/build/distroless-iptables/distroless/package-utils.sh
  images/build/distroless-iptables/distroless/stage-binaries-from-package.sh
  images/build/distroless-iptables/distroless/stage-binary-and-deps.sh
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2606 Switch to `github.com/blang/semver/v4`
  cmd/krel/cmd/release_notes.go
  go.mod
  go.sum
  packages/deb/build.go
  packages/deb/go.mod
  packages/deb/go.sum
  pkg/anago/anago.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/anagofakes/fake_stage_impl.go
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/changelog/changelog.go
  pkg/changelog/changelog_test.go
  pkg/changelog/changelogfakes/fake_impl.go
  pkg/changelog/impl.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/gcbfakes/fake_release.go
  pkg/kubepkg/kubepkg.go
  pkg/release/branch_checker.go
  pkg/release/branch_checker_test.go
  pkg/release/push_git_objects.go
  pkg/release/version_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2610 golang: build 1.19rc2 images
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, priority/important-soon, sig/release, area/release-eng

#2609 debian-base: Build bullseye-v1.4.1
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, priority/important-soon, sig/release, ok-to-test, area/release-eng, area/dependency, area/release-eng/security

#2613 Bumping distroless-iptables to 0.1.1 to patch vulnerability
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#2615 update cosign image to use release v1.10.0
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2621 [GO] build Go 1.18.4 and 1.17.12 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2622 k8s-cloud-builder/k8s-ci-builder: build using go1.18.4 and go1.17.12
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority
