Repository kubernetes/release, pull requests merged in 2022-09, with the labels that each got.

#2659 Build Go 1.19.1 and 1.18.6 based images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2660 Bump k8s-cloud-builder and k8s-ci-builder to Go 1.19.1 and Go 1.18.6
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2664 krel: Support Tempral CVE metrics
  pkg/cve/cve.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2666 Switch to goark/go-cvss
  go.mod
  go.sum
  pkg/cve/cve.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2672 Use CVE `Metrics` interface to simplify code
  pkg/cve/cve.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2673 Use latest CNI version for deb packages
  dependencies.yaml
  packages/deb/build.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#2665 update ci-signal tool reviewers
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, tide/merge-method-squash, area/release-eng, needs-priority

#2667 distroless-iptables: bump gorunner image version to v2.3.1-go1.19.1
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, ok-to-test, area/release-eng, needs-priority

#2682 update GORUNNER_VERSION base image for debian-iptables
  dependencies.yaml
  images/build/debian-iptables/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#2685 Fix command name in publish-release README.md
  cmd/publish-release/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/documentation, kind/cleanup, area/release-eng, needs-priority
