Repository kubernetes/release, pull requests merged in 2022-02, with the labels that each got.

#2408 Add `ok-to-test` label to dependabot PRs
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2410 Fix bug where incorrect count was used when assets had no tag
  cmd/publish-release/cmd/github.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2411 golang: Build 1.18beta2 images
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2413 Clone tool repo on krel fast-forward
  pkg/fastforward/fastforward.go
  pkg/fastforward/fastforward_test.go
  pkg/fastforward/fastforwardfakes/fake_impl.go
  pkg/fastforward/impl.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2414 krel/ff: add an option to define a gcp project to use instead of the default one
  cmd/krel/cmd/ff.go
  pkg/fastforward/fastforward.go
  pkg/release/release.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2424 Fix krel fast-forward log bucket
  pkg/fastforward/fastforward.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#2419 Write the CI Signal report to a file & markdown formatting
  cmd/ci-reporter/cmd/root.go
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, tide/merge-method-squash, area/release-eng, needs-priority

#2426 [go] Build Go 1.17.7 and 1.16.14 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2421 fixed release-notes ssh git checkout website pr
  cmd/krel/cmd/release_notes.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2428 k8s-cloud-builder/k8s-ci-builder: build using Go 1.17.7
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2429 k8s-cloud-builder/k8s-ci-builder: build using Go 1.17.7 / 1.16.14
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2430 Update the Go update issue template
  .github/ISSUE_TEMPLATE/dep-golang.md
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, area/dependency, needs-priority

#2434 deps: Update to cosign v1.5.2
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, area/dependency, needs-priority, area/release-eng/security

#2437 k8s-cloud-builder: Build go1.18rc1 variant
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2431 Add s390x support to kube-cross image
  images/build/cross/Makefile
  images/build/cross/default/Dockerfile
  images/build/cross/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, ok-to-test, area/release-eng, area/dependency, needs-priority

#2438 Bump `github.com/docker/distribution` to `v2.8.0`
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2440 Increase build timeout
  images/build/cross/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, needs-ok-to-test, release-note-none, sig/release, needs-kind, area/release-eng, area/dependency, needs-priority

#2441 .github: Initial config for CodeQL & Scorecard
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/scorecards-analysis.yml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority, area/release-eng/security

#2442 Code scanning (part two)
  .github/workflows/codeql-analysis.yml
  .github/workflows/scorecards-analysis.yml
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority, area/release-eng/security

#2439 Link container images in changelog to GCR
  pkg/notes/document/document.go
  pkg/notes/document/document_test.go
  pkg/notes/document/template.go
  pkg/notes/document/testdata/document.md.golden
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority
