Repository kubernetes/release, pull requests merged in 2022-05, with the labels that each got.

#2515 Update ci-reporter project board filtering
  cmd/ci-reporter/cmd/github.go
  cmd/ci-reporter/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#2516 Allow fastforward to run non-interactive
  pkg/fastforward/fastforward.go
  pkg/gcp/gcb/gcb.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2517 Bump cri-tools to v1.24.0
  packages/deb/build.go
  packages/deb/build_test.go
  packages/rpm/kubelet.spec
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2524 Fix changelog generation for custom forks
  pkg/anago/stage.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#2521 [GO] build Go 1.18.2 and 1.17.10 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2526 k8s-cloud-builder/k8s-ci-builder: build using go1.18.2 and go1.17.10
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2527 Replace git.io URLs with the full URL to which they redirect
  .github/workflows/codeql-analysis.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2518 debian-base: Build bullseye-v1.3.0
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note-none, priority/important-soon, sig/release, ok-to-test, area/release-eng

#2531 remove check for outdated dependencies
  compile-release-tools
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note, priority/important-soon, sig/release, kind/cleanup, area/release-eng

#2534 Update docs to use "go install"
  cmd/release-notes/README.md
  cmd/schedule-builder/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#2535 Bump cri-tools to v1.24.2
  packages/deb/build.go
  packages/deb/build_test.go
  packages/rpm/kubelet.spec
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority
