Repository kubernetes/release, pull requests merged in 2023-07, with the labels that each got.

#3127 debian-base: switch to debian bookworm
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/bookworm/Dockerfile
  images/build/debian-base/bookworm/Dockerfile.build
  images/build/debian-base/bookworm/clean-install
  images/build/debian-base/bookworm/excludes
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3137 Remove old google analytics code
  images/build/debian-iptables/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#3136 debian-iptables: switch to debian bookworm
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/bookworm/Dockerfile
  images/build/debian-iptables/bookworm/iptables-wrapper
  images/build/debian-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3142 Replace the deprecated deadline flag with timeout in .golangci.yaml
  .golangci.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3143 update golangci-lint to v1.53
  .github/workflows/lint.yml
  .golangci.yml
  dependencies.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3144 build go images for 1.26/1.25/1.24 release branches
  dependencies.yaml
  images/build/cross/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3145 Bump builders to use Go 1.20.5 for branches 1.26/1.25/1.24
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3139 setcap: switch to debian bookworm
  dependencies.yaml
  images/build/setcap/Dockerfile
  images/build/setcap/Makefile
  images/build/setcap/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3150 releng-ci: switch to debian bookworm
  dependencies.yaml
  images/releng/ci/Dockerfile
  images/releng/ci/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3154 Build Go 1.20.6 images and remove references to Go 1.19
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#3153 Remove debian-iptables image
  .github/ISSUE_TEMPLATE/dep-golang.md
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/OWNERS
  images/build/debian-iptables/README.md
  images/build/debian-iptables/bookworm/Dockerfile
  images/build/debian-iptables/bookworm/iptables-wrapper
  images/build/debian-iptables/cloudbuild.yaml
  images/build/debian-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3146 kube-cross v1.28: switch to debian bookworm
  dependencies.yaml
  images/build/cross/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3147 kube-cross: update protobuf version
  dependencies.yaml
  images/build/cross/default/Dockerfile
  images/build/cross/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3158 Update builders for release branches to Go 1.20.6
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3164 Mock tags per branch to avoid GitHub rate limit
  pkg/changelog/changelog.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/failing-test, release-note-none, sig/release, area/release-eng, needs-priority

#2942 Download zeitgeist binary directly
  dependencies.yaml
  go.mod
  go.sum
  hack/verify-dependencies.sh
  internal/tools.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, lifecycle/rotten, kind/cleanup, area/release-eng, needs-priority

#3165 Add rpmlintrc file for kubelet
  cmd/krel/templates/latest/kubelet/kubelet.rpmlintrc
  cmd/krel/templates/latest/kubelet/kubelet.spec
  pkg/obs/specs/template.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3072 Fix typo at announce.go
  cmd/krel/cmd/announce.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3174 Fix OBS project substitution in GCB
  gcb/obs-release/cloudbuild.yaml
  gcb/obs-stage/cloudbuild.yaml
  pkg/gcp/gcb/gcb.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority, kind/regression

#3176 Make krel obs stage/release use correct OBSProject field
  pkg/obs/release.go
  pkg/obs/stage.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3178 Deflake `TestPublish` unit tests
  pkg/release/images_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/flake, area/release-eng, needs-priority
