Repository kubernetes/release, pull requests merged in 2023-09, with the labels that each got.

#3241 bump cosign image to v2.2.0
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3240 Update distroless-iptables image version to v0.3.1
  dependencies.yaml
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3249 Switch to bullseye for kube-cross
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3251 update k8s-ci-builder for go1.21 to use bullseye for 1.29 and default for next config keep on bookworm
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3253 Build Go 1.21.1 and 1.20.8 images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3254 Revert "Merge pull request #3223 from xmudrii/fix-release-comparison"
  pkg/release/publish.go
  pkg/release/publish_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority, kind/regression

#3257 Update k8s-cloud-builder/k8s-ci-builder to Go 1.21.1 after updating k/k master
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3258 Update distroless-iptables to use go 1.21.1
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3259 Update k8s-cloud-builder/k8s-ci-builder to Go 1.20.8
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3263 Update Dockerfile-kubepkg to use bookworm debian
  Dockerfile-kubepkg
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/failing-test, release-note-none, sig/release, area/release-eng, needs-priority

#3264 upgrade base image kubepkg-rpm to fedora:39
  Dockerfile-kubepkg-rpm
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/failing-test, release-note-none, sig/release, area/release-eng, needs-priority

#3229 Integrate CRI-O into `krel obs`
  cmd/krel/templates/latest/cri-o/cri-o.spec
  cmd/krel/templates/latest/metadata.yaml
  pkg/obs/consts/consts.go
  pkg/obs/obs.go
  pkg/obs/specs/archive.go
  pkg/obs/specs/specs.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3267 Allow string slices as `krel obs` arguments
  cmd/krel/cmd/obs_stage.go
  gcb/obs-stage/cloudbuild.yaml
  pkg/gcp/gcb/gcb.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3271 Make `--workspace` configurable in `obs stage/release`
  cmd/krel/cmd/obs_release.go
  cmd/krel/cmd/obs_stage.go
  pkg/obs/obs.go
  pkg/obs/obsfakes/fake_release_impl.go
  pkg/obs/obsfakes/fake_stage_impl.go
  pkg/obs/prerequisites.go
  pkg/obs/release.go
  pkg/obs/stage.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3272 Make `--template-dir` work for `krel obs release`
  cmd/krel/cmd/obs_release.go
  pkg/obs/release.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3273 Allow setting OBS_USERNAME for a specific user
  pkg/obs/obs.go
  pkg/obs/release.go
  pkg/obs/stage.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3274 Fix CRI-O unitdir macro on debbuild
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3275 Add registries.conf to CRI-O spec
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3277 Deprecate release notes website pr
  cmd/krel/cmd/release_notes.go
  docs/krel/release-notes.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, kind/deprecation, needs-priority

#3278 Update `osc` binary in k8s-cloud-builder
  images/k8s-cloud-builder/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3279 Fix EnvironmentFile path for kubeadm deb package
  cmd/krel/templates/latest/kubeadm/kubeadm.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, priority/critical-urgent, sig/release, area/release-eng, kind/regression

#3283 Use conmon and crun from CRI-O package
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3281 reverting parallel builds freal
  pkg/build/make.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, priority/important-soon, sig/release, kind/cleanup, area/release-eng

#3286 Fix integration tests
  cmd/krel/cmd/changelog_data_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/failing-test, release-note-none, sig/release, area/release-eng, needs-priority

#3287 cri-o: fix license and readme for deb build
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#3288 Fix specfile typo for variable
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3289 CRI-O: allow CNI plugins fallback package
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3290 CRI-O: handle systemd unit file
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3291 Fix logical `or` in CRI-O rpm spec
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3292 Don't start systemd unit by default
  cmd/krel/templates/latest/cri-o/cri-o.spec
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3293 Remove CRI-O spec
  cmd/krel/templates/latest/cri-o/cri-o.spec
  cmd/krel/templates/latest/metadata.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority
