Repository kubernetes/release, pull requests merged in 2023-11, with the labels that each got.

#3340 group dependencies updates
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3342 fix dependabot config
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3339 Fix typo
  cmd/release-notes/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, needs-kind, area/release-eng, needs-priority

#3346 update cosign image to v2.2.1
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3348 Build Go 1.21.4 and 1.20.11 images
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3350 Update distroless-iptables to use go 1.21.4
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3356 Update k8s-cloud-builder to go 1.21.4
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3358 Update k8s-cloud-builder/k8s-ci-builder to Go 1.20.11 and add missing for 1.21.4
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3359 Use latest krel binary release instead of compilation in cloudbuild
  docs/krel/README.md
  gcb/fast-forward/cloudbuild.yaml
  gcb/obs-release/cloudbuild.yaml
  gcb/obs-stage/cloudbuild.yaml
  gcb/release/cloudbuild.yaml
  gcb/stage/cloudbuild.yaml
  hack/get-krel
  pkg/gcp/gcb/gcb.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3362 Set `KUBE_CROSS_VERSION` to latest if required
  pkg/gcp/gcb/gcb.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, area/release-eng, needs-priority, kind/regression

#3363 Update zeitgeist to v0.4.3
  dependencies.yaml
  hack/verify-dependencies.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3364 Cleanup dependencies.yaml
  dependencies.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3312 add config for go1.20 for distroless-iptables
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/cloudbuild.yaml
  images/build/distroless-iptables/distroless-bookworm/Dockerfile
  images/build/distroless-iptables/distroless-bookworm/clean-distroless.sh
  images/build/distroless-iptables/distroless-bookworm/package-utils.sh
  images/build/distroless-iptables/distroless-bookworm/stage-binaries-from-package.sh
  images/build/distroless-iptables/distroless-bookworm/stage-binary-and-deps.sh
  images/build/distroless-iptables/distroless-bullseye/Dockerfile
  images/build/distroless-iptables/distroless-bullseye/clean-distroless.sh
  images/build/distroless-iptables/distroless-bullseye/package-utils.sh
  images/build/distroless-iptables/distroless-bullseye/stage-binaries-from-package.sh
  images/build/distroless-iptables/distroless-bullseye/stage-binary-and-deps.sh
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3366 update to go1.21 and bump dependencies
  .github/workflows/lint.yml
  dependencies.yaml
  go.mod
  go.sum
  images/build/go-runner/go.mod
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3377 bump release-sdk and go-github
  go.mod
  go.sum
  pkg/fastforward/fastforward_test.go
  pkg/fastforward/fastforwardfakes/fake_impl.go
  pkg/fastforward/impl.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority
