Repository kubernetes/release, pull requests merged in 2023-02, with the labels that each got.

#2887 golang: Build 1.20 images
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2888 Explicitly add docker buildx plugin in Dockerfile for `k8s-ci-builder`
  images/releng/k8s-ci-builder/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, priority/critical-urgent, release-note-none, sig/release, area/release-eng

#2891 Add Docker buildx version to `dependencies.yaml`
  dependencies.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2878 enforce harden runner policies
  .github/workflows/codeql-analysis.yml
  .github/workflows/depsreview.yml
  .github/workflows/scorecards-analysis.yml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#2892 Update golangci-lint and config
  .golangci.yml
  dependencies.yaml
  hack/verify-golangci-lint.sh
  pkg/packages/packages_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2895 Bump k8s-cloud-builder and k8s-ci-builder to Go 1.20
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2897 k8s-ci-builder: install ifconfig through net-tools
  images/releng/k8s-ci-builder/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, priority/critical-urgent, kind/failing-test, sig/release, area/release-eng

#2898 Update qemu to v7.2.0-1
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-iptables/Makefile
  images/build/setcap/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2908 update test `TestNewPatchRelease`
  cmd/krel/cmd/changelog_data_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2906 Cleanup
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/debian-iptables/Makefile
  images/build/go-runner/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#2915 update TestNewPatchRelease test
  cmd/krel/cmd/changelog_data_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2914 Build Go 1.20.1 and 1.19.6 based images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2872 releng: add cici37 as Release Manager
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, priority/important-soon, sig/release, kind/documentation, area/release-eng

#2905 Updated registry references to registry.k8s.io
  .github/workflows/scorecards-analysis.yml
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/README.md
  images/build/distroless-iptables/README.md
  images/build/setcap/Makefile
  images/build/setcap/README.md
  images/k8s-cloud-builder/Dockerfile
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, priority/important-soon, sig/release, kind/cleanup, area/release-eng, sig/k8s-infra

#2911 Remove Rendertron usage since it is deprecated
  cmd/krel/cmd/testgrid.go
Labels: lgtm, cncf-cla: yes, size/M, approved, priority/critical-urgent, release-note-none, sig/release, kind/cleanup, area/release-eng

#2921 Bump k8s-cloud-builder and k8s-ci-builder to Go 1.20.1 and 1.19.6
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#2920 Update go-runner version in distroless-iptables.
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#2918 Final updates for registry.k8s.io references
  images/build/distroless-iptables/Makefile
  pkg/announce/announce.go
  pkg/release/images_test.go
  push-build.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, priority/important-soon, sig/release, kind/cleanup, area/release-eng, sig/k8s-infra

#2925 Refresh debian-base image
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/buster/Dockerfile
  images/build/debian-base/buster/Dockerfile.build
  images/build/debian-base/buster/clean-install
  images/build/debian-base/buster/excludes
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2922 Add debian-iptables and distroless-iptables to ISSUE_TEMPLATE/dep-golang
  .github/ISSUE_TEMPLATE/dep-golang.md
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, priority/important-longterm, sig/release, kind/documentation, ok-to-test, area/release-eng

#2927 transition ci signal reporter reviewers from 1.26 to 1.27
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#2935 comment out temporarily the verify image signatures
  pkg/anago/release_test.go
  pkg/release/images.go
  pkg/release/images_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, priority/critical-urgent, release-note-none, sig/release, kind/cleanup, area/release-eng
