Repository kubernetes/release, pull requests merged in 2023-08, with the labels that each got.

#3184 Update version constraint for kubernetes-cni package
  cmd/krel/templates/latest/metadata.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3186 OBS specs: remove source tarball when downloading from GCS
  pkg/obs/specs/archive.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3187 Drop kubelet dependency for kubernetes-cni
  cmd/krel/templates/latest/kubernetes-cni/kubernetes-cni.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3188 Ability to build amd64 from arm64 as well
  images/build/cross/default/Dockerfile
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, needs-kind, area/release-eng, needs-priority

#3190 golang: build 1.21rc4 images
  dependencies.yaml
  images/build/cross/variants.yaml
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3191 Update dependencies for new deb and rpm packages
  cmd/krel/templates/latest/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/kubelet/kubelet.spec
  cmd/krel/templates/latest/metadata.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3197 Update distroless-iptables to use go 1.20.7
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3201 Update builders for release branches to Go 1.20.7
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3192 Update package dependencies for 1.28
  cmd/krel/templates/latest/metadata.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3198 update publishing-bot issue repo to k/sig-release
  pkg/release/release.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3211 docs: fix broken links to test dashboard
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/GetPullRequest-35.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListCommits-0.json
  cmd/krel/cmd/testdata/changelog-v1.18.0-alpha.3/ListPullRequestsWithCommit-21.json
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3212 build go1.21 images with base debian bookworm
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3216 fix link to example go-template for release tool
  cmd/release-notes/README.md
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/documentation, ok-to-test, area/release-eng, needs-priority

#3227 Remove workdir prefix from SHA*SUMS files
  pkg/release/release.go
  pkg/release/release_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3223 Fix version comparison in VerifyLatestUpdate
  pkg/release/publish.go
  pkg/release/publish_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3231 `krel obs specs`: Stronger defaults
  pkg/obs/consts/consts.go
  pkg/obs/obs.go
  pkg/obs/specs/specs.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3233 go-runner: switch to debian bookworm
  dependencies.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3235 distroless-iptables: provide debian 12 bookworm variant
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/distroless/package-utils.sh
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3236 Update distroless version to v0.3.0
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3237 distroless-iptables: fix `grep` command
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/distroless/Dockerfile
  images/build/distroless-iptables/distroless/package-utils.sh
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority
