Repository kubernetes/release, pull requests merged in 2023-05, with the labels that each got.

#3029 Build Go 1.20.4 and 1.19.9 based images
  Dockerfile-kubepkg
  Dockerfile-kubepkg-rpm
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
  packages/deb/Dockerfile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, area/dependency, needs-priority

#3031 update debian-iptables and distroless-iptables to go 1.20.4
  dependencies.yaml
  images/build/debian-iptables/Makefile
  images/build/debian-iptables/variants.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3032 Bump kube-cross and k8s-cloud-builder to go 1.20.4
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Dockerfile
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#3034 Bump k8s-cloud-builder and k8s-ci-builder to Go 1.19.9
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3038 Cleanup of unused verify-shellcheck.
  Makefile
  hack/verify-shellcheck.sh
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3041 update TestNewPatchRelease test
  cmd/krel/cmd/changelog_data_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3043 bump cosign to v2.0.2
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3061 update changelog test
  cmd/krel/cmd/changelog_data_test.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3066 Update package specs used for OBS
  cmd/krel/templates/latest/rpm/cri-tools/cri-tools.spec
  cmd/krel/templates/latest/rpm/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/rpm/kubectl/kubectl.spec
  cmd/krel/templates/latest/rpm/kubelet/kubelet.spec
  cmd/krel/templates/latest/rpm/kubernetes-cni/kubernetes-cni.spec
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3069 Fix typos
  cmd/ci-reporter/README.md
  cmd/krel/cmd/announce_build.go
  cmd/krel/cmd/announce_send.go
  cmd/krel/cmd/cve.go
  cmd/krel/cmd/ff.go
  cmd/krel/cmd/release_notes.go
  cmd/publish-release/cmd/github.go
  cmd/schedule-builder/cmd/markdown.go
  hack/packages/verify-published.sh
  hack/rapture/README.md
  hack/verify-golangci-lint.sh
  pkg/anago/anago.go
  pkg/anago/release.go
  pkg/anago/stage.go
  pkg/announce/github_page.go
  pkg/binary/binary_test.go
  pkg/fastforward/fastforward.go
  pkg/mail/mail_test.go
  pkg/release/archive.go
  pkg/release/branch_checker.go
  pkg/release/prerequisites.go
  pkg/release/provenance.go
  pkg/release/push_git_objects.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#3070 Revert "Update package specs used for OBS"
  cmd/krel/templates/latest/rpm/cri-tools/cri-tools.spec
  cmd/krel/templates/latest/rpm/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/rpm/kubectl/kubectl.spec
  cmd/krel/templates/latest/rpm/kubelet/kubelet.spec
  cmd/krel/templates/latest/rpm/kubernetes-cni/kubernetes-cni.spec
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, needs-kind, area/release-eng, needs-priority

#3071 Update packaging spec files for OBS
  cmd/krel/templates/latest/rpm/cri-tools/cri-tools.spec
  cmd/krel/templates/latest/rpm/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/rpm/kubectl/kubectl.spec
  cmd/krel/templates/latest/rpm/kubelet/kubelet.spec
  cmd/krel/templates/latest/rpm/kubernetes-cni/kubernetes-cni.spec
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3075 add go boilerplate when running go generate
  pkg/anago/anago.go
  pkg/binary/binary.go
  pkg/build/make.go
  pkg/changelog/impl.go
  pkg/fastforward/impl.go
  pkg/gcp/gcb/gcb.go
  pkg/kubecross/impl.go
  pkg/kubepkg/kubepkg.go
  pkg/mail/mail.go
  pkg/notes/dependencies.go
  pkg/obs/specs/specs.go
  pkg/packages/packagesfakes/fake_impl.go
  pkg/release/doc.go
  pkg/release/version.go
  pkg/testgrid/testgrid.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3073 update to set go1.20 in go.mod and upgrade golangci-lint
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  cmd/ci-reporter/cmd/github.go
  cmd/ci-reporter/cmd/root.go
  cmd/krel/cmd/sign_images.go
  dependencies.yaml
  go.mod
  hack/verify-golangci-lint.sh
  images/build/go-runner/go.mod
  packages/deb/go.mod
  pkg/anago/release.go
  pkg/build/push.go
  pkg/cve/impl.go
  pkg/kubecross/impl.go
  pkg/kubecross/kubecross.go
  pkg/kubecross/kubecrossfakes/fake_impl.go
  pkg/packages/packages_test.go
  pkg/release/images.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3078 Upgrade code to be compatible with cosign v2
  cmd/krel/cmd/sign_blobs.go
  gcb/release/cloudbuild.yaml
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XXL, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3081 bump release-sdk dependency
  cmd/krel/cmd/changelog_data_test.go
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3082 Update release-sdk to ade4629
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note-none, sig/release, area/release-eng, needs-priority

#3079 Refactor `krel obs specs` command
  cmd/krel/cmd/obs_specs.go
  cmd/krel/templates/latest/cri-tools/LICENSE
  cmd/krel/templates/latest/cri-tools/README.md
  cmd/krel/templates/latest/cri-tools/cri-tools.spec
  cmd/krel/templates/latest/kubeadm/10-kubeadm.conf
  cmd/krel/templates/latest/kubeadm/LICENSE
  cmd/krel/templates/latest/kubeadm/README.md
  cmd/krel/templates/latest/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/kubectl/LICENSE
  cmd/krel/templates/latest/kubectl/README.md
  cmd/krel/templates/latest/kubectl/kubectl.spec
  cmd/krel/templates/latest/kubelet/LICENSE
  cmd/krel/templates/latest/kubelet/README.md
  cmd/krel/templates/latest/kubelet/kubelet.env
  cmd/krel/templates/latest/kubelet/kubelet.service
  cmd/krel/templates/latest/kubelet/kubelet.spec
  cmd/krel/templates/latest/kubernetes-cni/LICENSE
  cmd/krel/templates/latest/kubernetes-cni/README.md
  cmd/krel/templates/latest/kubernetes-cni/kubernetes-cni.spec
  cmd/krel/templates/latest/metadata.yaml
  pkg/obs/metadata/metadata.go
  pkg/obs/options/options.go
  pkg/obs/options/options_test.go
  pkg/obs/specs/archive.go
  pkg/obs/specs/fetcher.go
  pkg/obs/specs/helpers.go
  pkg/obs/specs/links.go
  pkg/obs/specs/links_test.go
  pkg/obs/specs/specs.go
  pkg/obs/specs/specs_test.go
  pkg/obs/specs/specsfakes/fake_impl.go
  pkg/obs/specs/template.go
  pkg/obs/specs/versions.go
  pkg/obs/specs/versions_test.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3084 Add osc to k8s-cloud-builder image
  images/k8s-cloud-builder/Dockerfile
  images/k8s-cloud-builder/test.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#2780 Remove "Kubernetes Source Code" from being published on GitHub Releases
  pkg/anago/release.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3086 Improvements and bug fixes for `krel obs specs`
  cmd/krel/cmd/obs_specs.go
  go.mod
  go.sum
  pkg/obs/consts/consts.go
  pkg/obs/options/options.go
  pkg/obs/specs/archive.go
  pkg/obs/specs/helpers.go
  pkg/obs/specs/impl.go
  pkg/obs/specs/pkgdef.go
  pkg/obs/specs/specs.go
  pkg/obs/specs/specsfakes/fake_impl.go
  pkg/obs/specs/template.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3093 Inline value for certificate-identity in GCB release
  gcb/release/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority, kind/regression

#3020 Add SBOM format flag to publish-release
  cmd/publish-release/cmd/github.go
  compile-release-tools
  pkg/announce/github_page.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3094 Fix package versioning and package sources extracting in `krel obs specs` subcommand
  cmd/krel/templates/latest/cri-tools/cri-tools.spec
  cmd/krel/templates/latest/kubeadm/kubeadm.spec
  cmd/krel/templates/latest/kubectl/kubectl.spec
  cmd/krel/templates/latest/kubelet/kubelet.spec
  cmd/krel/templates/latest/kubernetes-cni/kubernetes-cni.spec
  go.mod
  go.sum
  pkg/anago/anago.go
  pkg/anago/stage.go
  pkg/obs/specs/archive.go
  pkg/obs/specs/pkgdef.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority
