Repository kubernetes/release, pull requests merged in 2024-05, with the labels that each got.

#3591 Mark text/template usage safe from yaml injection.
  cmd/schedule-builder/cmd/markdown.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3596 `pkg/announce`: make interface functions public and add tests
  pkg/announce/announce.go
  pkg/announce/announce_test.go
  pkg/announce/announcefakes/fake_impl.go
  pkg/announce/impl.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3602 Update golangci-lint to v1.58.0 and fix lints
  .github/workflows/lint.yml
  .golangci.yml
  dependencies.yaml
  pkg/notes/notes_gatherer_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3604 Build Go 1.22.3 and 1.21.10
  dependencies.yaml
  hack/verify-dependencies.sh
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3605 bump distroless to use go1.22.3 and go1.21.10
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3611 Update `schedule-builder` docs
  cmd/schedule-builder/README.md
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/documentation, area/release-eng, needs-priority

#3612 rebuild debian-base - bump to bookworm-v1.0.3
  dependencies.yaml
  images/build/debian-base/Makefile
  images/build/debian-base/variants.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3613 Build k8s-ci-builder and k8s-cloud-bulider with Go 1.22.3 for k/k main
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3615 Fix error message for `err == nil`
  pkg/anago/stage.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3618 Build k8s-ci-builder and k8s-cloud-bulider with Go 1.21.10/1.22.3
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3625 Fix path for kubelet.env file in kubelet deb package
  cmd/krel/templates/latest/kubelet/kubelet.spec
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, priority/important-soon, sig/release, area/release-eng

#3616 Fix version comparison for final version after RC
  pkg/release/publish.go
  pkg/release/publish_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority
