Repository kubernetes/release, pull requests merged in 2024-10, with the labels that each got.

#3764 Fix empty release note parsing
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3765 Add krel validate cmd
  cmd/krel/cmd/testdata/validation-data/invalid-indent.yaml
  cmd/krel/cmd/testdata/validation-data/invalid-multi-line.yaml
  cmd/krel/cmd/testdata/validation-data/invalid-yaml-start.yaml
  cmd/krel/cmd/testdata/validation-data/missing-punctuation.yaml
  cmd/krel/cmd/testdata/validation-data/valid.yaml
  cmd/krel/cmd/validate.go
  cmd/krel/cmd/validate_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3781 revert go 1.23 changes to fix pull-release-image-k8s-ci-builder
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yaml
  .golangci.yml
  dependencies.yaml
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, ok-to-test, area/release-eng, needs-priority, kind/regression

#3790 GitHub actions: still use go 1.23
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/snapshot.yaml
  .golangci.yml
  dependencies.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3793 Use only public URLS for release notes index
  pkg/release/publish.go
  pkg/release/publish_test.go
  pkg/release/release.go
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3779 build kube-cross, go-runner, releng-ci with golang 1.22.8, 1.23.2
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, ok-to-test, area/release-eng, needs-priority

#3797 bump distroless-iptables to use go 1.22.8/1.23.2
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, priority/critical-urgent, sig/release, ok-to-test, area/release-eng

#3799 Update k8s-cloud-builder and k8s-ci-builder for Kubernetes 1.32 to Go 1.23.2
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3800 Tidy `dependencies.yaml` file
  dependencies.yaml
  images/build/cross/Makefile
  images/build/go-runner/Makefile
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3801 Add clarification comments to `dependencies.yaml`
  dependencies.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3803 Fix krel announcement --print-only
  cmd/krel/cmd/announce_send.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3804 update github.com/yuin/goldmark and go.mod to default to go1.22.8
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3805 upgrade zeitgeist to v0.5.4
  dependencies.yaml
  hack/verify-dependencies.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3806 upgrade cosign to v2.2.4
  dependencies.yaml
  images/build/go-runner/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, needs-kind, area/release-eng, needs-priority

#3807 Update k8s-cloud-builder and k8s-ci-builder to Go 1.22.8/1.23.2
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, ok-to-test, area/release-eng, needs-priority
