Repository kubernetes/release, pull requests merged in 2024-04, with the labels that each got.

#3536 add bom and attestation to release jobs
  .github/workflows/release.yml
  .github/workflows/snapshot.yaml
  .goreleaser.yml
  .krel-bom-config.yaml
  .publish-release-bom-config.yaml
  .release-notes-bom-config.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3530 Update sigs.k8s.io/bom to v0.6.0 and drop build for linux/s390x and windows/386
  go.mod
  go.sum
  hack/verify-build.sh
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note, sig/release, kind/cleanup, area/release-eng, needs-priority

#3538 Compare original PR body on release notes mapping
  cmd/krel/cmd/release_notes.go
  go.mod
  pkg/notes/notes.go
  pkg/notes/notes_map.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3541 Fix schedule builder to reflect current format
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
  cmd/schedule-builder/cmd/model.go
  cmd/schedule-builder/cmd/root.go
  cmd/schedule-builder/cmd/root_test.go
  cmd/schedule-builder/cmd/testdata/schedule.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3543 Streamline schedule builder flags
  cmd/schedule-builder/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3542 Add `schedule-builder` to release job
  .goreleaser.yml
  .schedule-builder-bom-config.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3544 Add `--update` flag to `schedule-builder`
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
  cmd/schedule-builder/cmd/model.go
  cmd/schedule-builder/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3547 Add upcoming monthly releases support to schedule-builder
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
  cmd/schedule-builder/cmd/model.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3548 Add `--version/-v` flag to `schedule-builder`
  cmd/schedule-builder/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3550 Add `-e/--eol-config-path` support to `schedule-builder`
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
  cmd/schedule-builder/cmd/model.go
  cmd/schedule-builder/cmd/root.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3551 Don't panic if next release is not set
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3549 Build Go 1.22.2 and 1.21.9
  dependencies.yaml
  images/build/cross/Makefile
  images/build/cross/variants.yaml
  images/build/go-runner/Makefile
  images/build/go-runner/variants.yaml
  images/releng/ci/Dockerfile
  images/releng/ci/variants.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3554 bump distroless to use go1.22.2 and go1.21.9
  dependencies.yaml
  images/build/distroless-iptables/Makefile
  images/build/distroless-iptables/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3556 revert go.mod to accept minimum go 1.21
  dependencies.yaml
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3558 bump release-utils to v0.8.1
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3555 Build k8s-ci-builder and k8s-cloud-bulider with Go 1.22.2
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/Makefile
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3561 Build k8s-ci-builder and k8s-cloud-bulider with Go 1.21.9
  dependencies.yaml
  images/k8s-cloud-builder/variants.yaml
  images/releng/k8s-ci-builder/variants.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3559 Set GitHub release as latest if target release is highest semver
  go.mod
  pkg/announce/github_page.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/feature, release-note, sig/release, ok-to-test, area/release-eng, needs-priority

#3569 Ensure `make update-mocks` does not inject existing boilerplate
  Makefile
  pkg/release/releasefakes/fake_publisher_client.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3570 Do not add release name for upcoming releases
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3577 schedule-builder: fix wrong log message
  cmd/schedule-builder/cmd/markdown.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3578 Fix monthly patch output for schedule-builder
  cmd/schedule-builder/cmd/markdown.go
  cmd/schedule-builder/cmd/markdown_test.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, release-note, sig/release, area/release-eng, needs-priority

#3579 Remove already enabled gocritic linters from config
  .golangci.yml
Labels: lgtm, cncf-cla: yes, size/M, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3583 schedule-builder: Add markdown help
  cmd/schedule-builder/cmd/markdown.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/feature, release-note, sig/release, area/release-eng, needs-priority

#3580 Refactor `pkg/announce` package into sub-packages and interface pattern
  cmd/publish-release/cmd/github.go
  pkg/anago/anagofakes/fake_release_impl.go
  pkg/anago/release.go
  pkg/announce/announce.go
  pkg/announce/announcefakes/fake_impl.go
  pkg/announce/github/consts.go
  pkg/announce/github/github.go
  pkg/announce/github/githubfakes/fake_impl.go
  pkg/announce/github/impl.go
  pkg/announce/github/options.go
  pkg/announce/github_page.go
  pkg/announce/impl.go
  pkg/announce/sbom/impl.go
  pkg/announce/sbom/options.go
  pkg/announce/sbom/sbom.go
  pkg/announce/sbom/sbomfakes/fake_impl.go
Labels: lgtm, cncf-cla: yes, size/XXL, approved, release-note-none, sig/release, kind/cleanup, ok-to-test, area/release-eng, needs-priority

#3590 Enable and fix `perfsprint` linter
  .golangci.yml
  cmd/gcbuilder/cmd/root.go
  cmd/krel/cmd/release_notes.go
  cmd/krel/cmd/root.go
  cmd/publish-release/cmd/root.go
  cmd/release-notes/check.go
  cmd/schedule-builder/cmd/root.go
  pkg/anago/anago.go
  pkg/anago/stage.go
  pkg/announce/impl.go
  pkg/build/ci.go
  pkg/build/make.go
  pkg/gcp/build/build.go
  pkg/gcp/gcb/gcb.go
  pkg/gcp/gcb/history.go
  pkg/mail/mail.go
  pkg/mail/mail_test.go
  pkg/notes/document/document_test.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_v2.go
  pkg/obs/obs.go
  pkg/release/branch_checker.go
  pkg/release/release.go
  pkg/release/repository.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority
