Repository kubernetes/release, pull requests merged in 2025-03, with the labels that each got.

#3946 Fix bucket usage, now correctly pointing at GH for Krel release
  hack/get-krel
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, release-note-none, sig/release, area/release-eng, needs-priority

#3951 Remove duplicate kube-cross image pushes
  images/build/cross/cloudbuild.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority

#3964 Switch to golangci-lint v2
  .github/workflows/lint.yml
  .golangci.yml
  dependencies.yaml
  gcb/gcb.go
  pkg/anago/anago.go
  pkg/announce/announce.go
  pkg/announce/github/github.go
  pkg/announce/sbom/sbom.go
  pkg/binary/windows.go
  pkg/build/make.go
  pkg/changelog/changelog.go
  pkg/notes/notes.go
  pkg/notes/notes_gatherer_test.go
  pkg/notes/notes_test.go
  pkg/notes/notes_v2.go
  pkg/obs/obs.go
  pkg/obs/specs/archive.go
  pkg/obs/specs/helpers.go
  pkg/obs/specs/pkgdef.go
  pkg/obs/specs/template.go
  pkg/release/provenance_test.go
  pkg/release/publish.go
  pkg/release/release_version.go
  pkg/release/repository.go
  pkg/testgrid/testgrid-scraper_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, release-note-none, sig/release, kind/cleanup, area/release-eng, needs-priority
